### ISSUE TITLE
Don't truncate trailing slashes in urls.

### ISSUE THREAD

**Issue by hooliooo** [lejard-h/chopper#1]
Hi there,

I'm currently using this library in a Flutter project and I am working with an API with explicit trailing slashes in the endpoints (it's a security feature not a bug).

 I noticed that the Request's url automatically truncates the trailing slash of any url.

Is it possible to not do this? The current workaround I have for this is to explicitly put two trailing slashes.

I end up with a setup like this:

```dart
@ChopperApi('HomeService')
abstract class HomeServiceDefinition {

  @Get(url: 'user/widgets//')
  Future<Response> getProfitCenters();

  @Get(url: 'user/otherwidgets//')
  Future<Response> getUsers();
}
```

instead of:

```dart
@ChopperApi('HomeService')
abstract class HomeServiceDefinition {

  @Get(url: 'user/widgets/')
  Future<Response> getProfitCenters();

  @Get(url: 'user/otherwidgets/')
  Future<Response> getUsers();
}
```

**Comment by lejard-h** [comment]
Hey, could you test with the last version ? `0.1.0`
Thanks :)

**Comment by SyedAhkam** [comment]
Sorry for the bump but this issue still persists. Was it ever even fixed?

Using the `user/resource//` workaround for now.
