### ISSUE TITLE
Interceptor doesn't get the correct HTTP request

### ISSUE THREAD

**Issue by edwardaux** [lejard-h/chopper#10]
I wanted to write an interceptor that would dump out a `curl` command for each `Request`. However, the `request` object that is passed to the interceptor doesn't have everything it needs. 

For example, it doesn't contain the `baseUrl` and none of the "body" processing logic has been performed. In theory, the interceptor could call `toHttpRequest(...)` however a) it doesn't have the input params it needs, and b) that is leaking out internal knowledge of how `ChopperClient.send()` works.

One possibility is to change the Interceptor API so that it takes the output of `req.toHttpRequest(...)`. This would be a breaking change however.

Of course, there's a chance that I've missed a different way of being able to log the contents of a request. Just let me know... :) 

I'm happy to contribute my interceptor back to the chopper project to be included as an out-of-the-box helper if you like.

**Comment by lejard-h** [comment]
About the body encoded, it is linked to this 

https://github.com/lejard-h/chopper/issues/6 (last part of my comments)

**Comment by edwardaux** [comment]
#6 is an interesting discussion... I have some thoughts on how that should/could work too 😄 ... I'll add them in that ticket. 

In terms of this issue, I feel like it would make more sense that the interceptor be given a copy of `http.BaseRequest` which will contain everything we need to properly log / modify.

**Comment by edwardaux** [comment]
Apologies for the delay in getting back to you on this. I finally had a chance to pull down the latest code. I can see that the `Request.toHttpRequest()` function is now available, and I can write a `CurlInterceptor` that generates and prints a curl command.

I can't test it at the moment though... for some reason, `build_runner` isn't actually generating my `service.chopper.dart` file (I can see that it has generated it in the `.dart_tool` directory, but it doesn't seem to copy over into my project properly. I don't think this is a Chopper problem... I'm just trying to work out how to pound `build_runner` into submission :)  I'll be back...

**Comment by edwardaux** [comment]
OK, I sorted out why things weren't generating properly (see #14). Once I fixed that, I wrote the following `CurlInterceptor` which seems to be working well (it doesn't handle multi-part yet, but is a good start). Feel free to include in the chopper package as a bundled interceptor.

```
class CurlInterceptor implements RequestInterceptor {
  Future<Request> onRequest(Request request) async {
    final baseRequest = await request.toHttpRequest();
    final method = baseRequest.method;
    final url = baseRequest.url.toString();
    final headers = baseRequest.headers;
    var curl = '';
    curl += 'curl';
    curl += ' -v';
    curl += ' -X $method';
    headers.forEach((k, v) {
      curl += ' -H \'$k: $v\'';
    });
    // this is fairly naive, but it should cover most cases
    if (baseRequest is http.Request) {
      final body = baseRequest.body;
      if (body != null && body.isNotEmpty) {
        curl += ' -d \'$body\'';
      }
    }
    curl += ' $url';
    print(curl);
    return request;
  }
}```

**Comment by lejard-h** [comment]
`2.0.0 released`
