### ISSUE TITLE
incompatible with built_value_generator ^6.7.1

### ISSUE THREAD

**Issue by MahdiPishguy** [lejard-h/chopper#100]
```bash
Because chopper_generator >=3.0.1 depends on analyzer ^0.38.2 and built_value_generator 
6.7.1 depends on analyzer >=0.34.0 <0.37.0, chopper_generator >=3.0.1 is incompatible 
with built_value_generator 6.7.1.

And because no versions of built_value_generator match >6.7.1 <7.0.0, chopper_generator 
>=3.0.1 is incompatible with built_value_generator ^6.7.1.

So, because cheetah depends on both built_value_generator ^6.7.1 and chopper_generator
 ^3.0.1, version solving failed.
pub get failed (1)
```

**Comment by erluxman** [comment]
Did you find anything on this?

**Comment by erluxman** [comment]
For now using chopper version 3.0.0 solved temporarily

**Comment by MahdiPishguy** [comment]
@erluxman for new version of `chopper` i can't solve that

**Comment by erluxman** [comment]
Yeah same here,

**Comment by lejard-h** [comment]
Sorry but it won't be fix on chopper side
Chopper use the latest version of analyzer (^0.38.2), 
while `built_value_generator` is using an older one (>=0.34.0 <0.37.0)

**Comment by erluxman** [comment]
I fixed it by making a fork from the google repo and updating the analyzer version and then making a release of it. it fixed the issue for me.

You can you this inject git instead 

https://github.com/erluxman/inject.dart
