### ISSUE TITLE
Use custom DNS server?

### ISSUE THREAD

**Issue by Jparrgam** [lejard-h/chopper#104]
There's no way to use a custom DNS server, or manually use another IP address to connect to a server.

**Comment by JEuler** [comment]
https://github.com/dart-lang/sdk/issues/36551 https://github.com/dart-lang/http/issues/222

As I understand, there are no such functionality in http package. One can use the OkHttp native extension for Android for example and create somekind of proxy. 

Or you can look at https://github.com/dart-protocol/dns

**Comment by Sominemo** [comment]
This functionally would be really useful for transparent HTTP proxies. Right now to accomplish this kind of trick, you need to work with dart:Io on low level to be able to intercept the Host header, so it makes developers to reimplement built in methods like HttpClient.post.

**Comment by stewemetal** [comment]
Closing this issue as it's old and inactive. Feel free to reopen.
