### ISSUE TITLE
Switching to a 'debugPrint' only affects responses

### ISSUE THREAD

**Issue by dpioempx** [lejard-h/chopper#105]
When using recommended logging setup and switching from 'print' to a 'debugPrint' for long messages it only affects logging responses while requests are cut off.

`  
Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((rec) {
    debugPrint('${rec.level.name}: ${rec.time}: ${rec.message}');
  });
`

**Comment by lejard-h** [comment]
`debugPrint` is related to flutter and I think it's the wanted behavior.
Switch back to `print` or use a logging library like [f_logs](https://pub.dev/packages/f_logs)
