### ISSUE TITLE
How to upload multipart?

### ISSUE THREAD

**Issue by tony123S** [lejard-h/chopper#106]
How to upload multipart? The image variable is the url of the image.

 ```
Future<Response> submit(
      BuildContext context,  String image) async {
    Response response;
    try {
    
      response = await _service.submit(image);
      return response;
    } catch (e) {
     ...
    }
  }
```

**service**

```
 @Post(path: "create")
  @multipart
  Future<Response> submit(@Part('image') prefix0.Multipart file);
```

How can I convert String to Multipart?

**Comment by lejard-h** [comment]
Hi @tony123S 

1. using an import alias with code generation won't work `prefix0.Multipart` (see: https://github.com/lejard-h/chopper/issues/75)

2. Use the `PartFile` annotation to send file using a path

```dart
@Post(path: "create")
@multipart
Future<Response> submit(@PartFile('image') String imagePath);
```

**Comment by fryette** [comment]
@lejard-h but what if I don;t have an imagePath?

I only have an bytearray and can create a MultipartFile
