### ISSUE TITLE
Please update analyzer version

### ISSUE THREAD

**Issue by windrunner414** [lejard-h/chopper#109]
pr here #110 

Because every version of copy_with_extension_gen depends on analyzer >=0.39.0 <1.0.0 and chopper_generator 3.0.3 depends on analyzer ^0.38.2, copy_with_extension_gen is incompatible with chopper_generator 3.0.3.

And because no versions of chopper_generator match >3.0.3 <4.0.0, copy_with_extension_gen is incompatible with chopper_generator ^3.0.3.

So, because wechat depends on both chopper_generator ^3.0.3 and copy_with_extension_gen ^1.0.7, version solving failed.
pub get failed (1; So, because wechat depends on both chopper_generator ^3.0.3 and copy_with_extension_gen ^1.0.7, version solving failed.)

**Comment by fryette** [comment]
any news on it?

**Comment by MahdiPishguy** [comment]
@windrunner414 how we can change that by hand?

**Comment by windrunner414** [comment]
@MahdiPishguy [my fork](https://github.com/windrunner414/chopper)

**Comment by chunghha** [comment]
Please see the analyzer version can be updated.

> Because mobx_codegen >=0.4.2 depends on build_resolvers ^1.3.2 which depends on analyzer ^0.39.0, mobx_codegen >=0.4.2 requires analyzer ^0.39.0.
> And because chopper_generator 3.0.3 depends on analyzer ^0.38.2 and no versions of chopper_generator match >3.0.3 <4.0.0, mobx_codegen >=0.4.2 is incompatible with chopper_generator ^3.0.3.

**Comment by MahdiPishguy** [comment]
> 
> 
> Please see the analyzer version can be updated.
> 
> > Because mobx_codegen >=0.4.2 depends on build_resolvers ^1.3.2 which depends on analyzer ^0.39.0, mobx_codegen >=0.4.2 requires analyzer ^0.39.0.
> > And because chopper_generator 3.0.3 depends on analyzer ^0.38.2 and no versions of chopper_generator match >3.0.3 <4.0.0, mobx_codegen >=0.4.2 is incompatible with chopper_generator ^3.0.3.

you can use `retrofit.dart` package

**Comment by JEuler** [comment]
Please merge it :)

**Comment by amebrahimi** [comment]
We are waiting for updating this analyzer dependency, please.

**Comment by WinnLeong** [comment]
This is conflicting with a package I use and it's failing when installing dependencies in codemagic build. Really hope there will be an update.

**Comment by windrunner414** [comment]
Maybe this package is no longer maintained, I'm thinking about moving to another package

**Comment by WinnLeong** [comment]
Sadly this is true, I am considering moving as well if there are still no updates.

**Comment by amebrahimi** [comment]
It's the best library for network requests. It's so sad if no longer maintained

**Comment by MahdiPishguy** [comment]
> 
> 
> We are waiting for updating this analyzer dependency, please.

I've been waiting since 6 months ago, Isn't that enough time? :face_with_head_bandage:

**Comment by lejard-h** [comment]
I have been struggling to find time to address all issues and PR on GitHub over the past couple of months.

I will try to work on chopper next week.

However I know that I can't be 100% on it anymore, I would be happy to co maintain the package. If someone is interested, you can reach me by email.

**Comment by windrunner414** [comment]
@lejard-h Good news! Thanks for your work

**Comment by fryette** [comment]
> I have been struggling to find time to address all issues and PR on GitHub over the past couple of months.
> 
> I will try to work on chopper next week.
> 
> However I know that I can't be 100% on it anymore, I would be happy to co maintain the package. If someone is interested, you can reach me by email.

maybe u can create a separate issue with this note, to find right people for contributing and supporting this great library

**Comment by lejard-h** [comment]
Thanks for your patience, I just published the last version
chopper `3.0.2`
chopper_generator `3.0.4`
