### ISSUE TITLE
How to show Logging Request and Response

### ISSUE THREAD

**Issue by kimbummen** [lejard-h/chopper#11]
Something like HttpLoggingInterceptor in retrofit. Can you show to me example code about that?

**Comment by lejard-h** [comment]
There is an undergoing discussion about interceptors orders and and Logger was mentionned
https://github.com/lejard-h/chopper/issues/6

but you can use following streams on ChopperClient to listen and log what you want

```
// just before sending request after all converters and interceptors
Stream<Request> get onRequest => _requestController.stream;

// if response is successfull (statusCode: 200>= <300)
Stream<Response> get onResponse => _responseController.stream;

// if not successful
Stream<Response> get onError => _responseErrorController.stream;
```

I will release the `1.2.0` in a few weeks I hope that will contain a builtin logger

**Comment by kimbummen** [comment]
> There is an undergoing discussion about interceptors orders and and Logger was mentionned
> #6
> 
> but you can use following streams on ChopperClient to listen and log what you want
> 
> ```
> // just before sending request after all converters and interceptors
> Stream<Request> get onRequest => _requestController.stream;
> 
> // if response is successfull (statusCode: 200>= <300)
> Stream<Response> get onResponse => _responseController.stream;
> 
> // if not successful
> Stream<Response> get onError => _responseErrorController.stream;
> ```
> I will release the `1.2.0` in a few weeks I hope that will contain a builtin logger

I'm hoping your new version. Thank your supporting.
