### ISSUE TITLE
Send parameter from body (form-data)

### ISSUE THREAD

**Issue by Lzyct** [lejard-h/chopper#111]
How to i send parameter from body like this  ?

![image](https://user-images.githubusercontent.com/1531684/71479981-e218b500-2831-11ea-9232-98776903d298.png)

**Comment by BirjuVachhani** [comment]
@lejard-h Any updates on this? I'm also facing some issues while trying to achieve this. I inspected curl request and it has empty data, meaning nothing is being sent in the curl request.

**Comment by krupalbhardiya** [comment]
Also need upload for **multiple files in single field** using form-data  request.



![Capture](https://user-images.githubusercontent.com/6060333/89005062-2ff22000-d321-11ea-8022-00ca6415cbff.PNG)

**Comment by Purvik** [comment]
@krupalbhardiya  Hey have you found any solution? I'm also stuck at the same part.

**Comment by krupalbhardiya** [comment]
@Purvik No.

> @krupalbhardiya Hey have you found any solution? I'm also stuck at the same part.

**Comment by conall1995** [comment]
any update for this?!Why!

**Comment by irangareddy** [comment]
Hey guys! stuck with the same issue. How can I resolve this?

**Comment by Rohithgilla12** [comment]
Hello still struck with this in 2022 :(

**Comment by Rohithgilla12** [comment]
Solution is to use `@multipart` decorator

**Comment by techouse** [comment]
@Rohithgilla12 does [this](https://hadrien-lejard.gitbook.io/chopper/requests#defining-fields-individually) answer your question?

**Comment by erlangparasu** [comment]
Did you try this

```dart
import 'package:chopper/chopper.dart';

  // ...

  @Post(
    path: '/api/books',
  )
  @Multipart()
  Future<Response<String>> storeBook({
    @Part('title') required String title,
    @Part('description') required String description,
    @PartFile('book_file') required String bookFilePath,
  });

  // ...
```

**Comment by erlangparasu** [comment]
See example comment: https://github.com/lejard-h/chopper/blob/7cd824cd3c37ee70cca1dfdbf1d0b1fe16c855c7/chopper/lib/src/annotations.dart#L379C20-L379C20

**Comment by erlangparasu** [comment]
https://github.com/lejard-h/chopper/issues/160#issuecomment-1693253774

**Comment by DreXuri** [comment]
you should try this either pass as string or a map. it works easy
![chopper](https://github.com/lejard-h/chopper/assets/80977358/71879ba5-f94e-4b39-a971-757db4215c7e)
