### ISSUE TITLE
@multipart

### ISSUE THREAD

**Issue by kufel** [lejard-h/chopper#112]
After upgrading to chopper: ^3.0.1+1 I am seeing issues @multipart not functioning properly anymore.

**Comment by kufel** [comment]
https://github.com/dart-lang/http/commit/29d326226d996bd8c2f57183a739ed2d12f713b5#diff-1bcc559d7868729b92bc2b01dec3c418

**Comment by ankitpanwar8979** [comment]
add http package "http: 0.12.0+4" in your pubspec.yaml file, then it will work.

**Comment by xellDart** [comment]
same error, on server site I get  let parsedName = fileName.length <= 255 ? fileName : fileName.substr(0, 255);
                            ^
TypeError: Cannot read property 'length' of undefined
