### ISSUE TITLE
GET Operation doesn't work properly

### ISSUE THREAD

**Issue by kdkanishka** [lejard-h/chopper#113]
This is my chopper api client code.

```dart
import 'package:chopper/chopper.dart';
import '/dto/employee.dart';

import 'customheader.dart';

part "employeeapiservice.chopper.dart";

@ChopperApi()
abstract class EmployeeApiService extends ChopperService {
  static EmployeeApiService create([ChopperClient client]) =>
      _$EmployeeApiService(client);

  @Get(path: "employee/list/company/{companyId}")
  Future<Response> getEmployeeListByCompanyId(
      @Header(CustomHeaders.AUTHORIZATION) String authorization,
      @Path("companyId") int companyId);
}
```
It works on android platform as expected. But on flutter web, not GET request issued but it makes an OPTION request as below.

I am using latest chopper version.
`chopper:` 3.0.1+1

 Screenshot
[https://imgur.com/a/MWIlQzo](url)

**Comment by lejard-h** [comment]
Every browser send an OPTIONS request for cross origin request.
Check if the server you call is correctly setting the CORS header

**Comment by kdkanishka** [comment]
Thanks a lot for the clarification.
