### ISSUE TITLE
class inside generated .g.dart file can't be used as Response<T>

### ISSUE THREAD

**Issue by Timo-Noordzee** [lejard-h/chopper#114]
It seems like chopper Response<T> isn't compatible with Moor generated classes. Moor generates a class called ActivityType inside a file called database.g.dart upon running flutter packages pub run build_runner build. I am trying to use this file as a type inside a  Future<Response<T>> as can be seen in the snippet below.

```
  @Get(path: '/Activity')
  Future<Response<List<ActivityType>>> getActivityTypes(@Query("token") String token, @Query("type") int type);
```

Upon running flutter packages pub run build_runner build my ActivityType class gets regenerated but it seems to happen after Chopper generates its .chopper.dart file. The .chopper.dart file contains the following after generating.

```
  @override
  Future<Response<List>> getActivityTypes(String token, int type) {
    final $url = '/api/Activity';
    final $params = <String, dynamic>{'token': token, 'type': type};
    final $request = Request('GET', $url, client.baseUrl, parameters: $params);
    return client.send<List, List>($request);
  }
```

As can be seen, the actual type (ActivityType) of the list is omitted thus assuming its type is dynamic. This results in the following error `'_$UrenAppAPI.getActivityTypes' ('Future<Response<List<dynamic>>> Function(String, int)') isn't a valid override of 'UrenAppAPI.getActivityTypes' ('Future<Response<List<ActivityType>>> Function(String, int)').`

When I use any class that isn't inside a generated file things seem to work fine.

**Comment by stewemetal** [comment]
While this issue may be a bug. using a (generated) class from the database handling part of the app in the network communication parts is kind of a bad practice.

Usually, your networking and database handling should not leak implementation details to each other. It requires a bit of work, but using a common "domain" level representation of your data can halp a lot, altough you would have to map you network and database classes to and from this representation.

For example, let's say you have a `NetworkActivityType` class for getting activity types from an API and you have a `MoorActivityType` class used with Moor. If you introduce a `DomainActivityType` class that you can map the aforementioned classes to and from, you can separate your database handling and neworking on a logical level. 😃 
Of course, in this example, you can replace the `MoorActivityType` class with the Moor-generated class, the emphasis is on the approach itself.

**Comment by stewemetal** [comment]
I've looked into this issue in more detail. My previous comment still stands, you shouldn't depend on generated classes in generated classes when you are the client of both generators (you're the app using both generators).

For this to work consistently, a client (app) would have to be able to define the order of how generators are run. This is currently not possible (a limitation of *source_gen* itself, [see this issue](https://github.com/dart-lang/source_gen/issues/442)).

That being the case, I'm closing this issue. Feel free to reopen it any time.
