### ISSUE TITLE
You need a MockInterceptor() for mock data

### ISSUE THREAD

**Issue by ozburo** [lejard-h/chopper#115]
How can we implement a Mock Data Interceptor like the one we have for DIO?
https://github.com/gabuldev/dio_interceptors/blob/master/lib/src/interceptor_mock.dart

I can see a way to _modify_ either the outgoing request or incoming response, but can't skip the request call (no need) and simply return a Map/Data.

Is this possible w/ Chopper? I think it would be a welcomed addition 👍

**Comment by lejard-h** [comment]
Chopper use `package:http`. 

You should be able to directly use the mocking API of the HTTP package.
https://pub.dev/documentation/http/latest/testing/MockClient-class.html

**Comment by ozburo** [comment]
For anyone wondering how to do this I just came back to this issue and refactored our app back to using Chopper and implemented mock data like this:

```
import 'dart:convert';

import 'package:chopper/chopper.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';

part 'api_service.chopper.dart';

@ChopperApi()
abstract class ApiService extends ChopperService {
  static ApiService create() {
    final client = ChopperClient(
      client: MockClient((request) async {
        Map result = mockData[request.url.path]?.firstWhere((d) {
          if (d['id'] == request.url.queryParameters['id']) return true;
          return false;
        }, orElse: () => null);
        if (result == null) {
          return http.Response(
              json.encode({'error': "not found"}), 404);
        }
        return http.Response(json.encode(result), 200);
      }),
      baseUrl: 'https://mysite.com/api',
      services: [
        _$ApiService(),
      ],
    );
    return _$ApiService(client);
  }

  @Get(path: "/get")
  Future<Response> get(@Query() String url);
}
```

It's easy and elegant once you know how 💯

**Comment by JEuler** [comment]
@ozburo Nice thing! Can we use this code for somekind of documentation about mocking? @lejard-h Are you agree? :)

**Comment by ozburo** [comment]
@JEuler that's why I posted it :blush:

**Comment by JEuler** [comment]
Thank you!

**Comment by JEuler** [comment]
Should we close this guys? :)

**Comment by JEuler** [comment]
Feel free to reopen :)
