### ISSUE TITLE
Optional @Path

### ISSUE THREAD

**Issue by ksmsk** [lejard-h/chopper#117]
example service method:
```dart
@Get(path: "topic/{topicId}/{category}/{searchQuery}")
  Future<Response<TopicContent>> getTopicContent({
    @required @Path() int topicId,
    @Path() String category,
    @Path() String searchQuery,
  });
```

If category and searchQuery are empty url string goes like `/topic/65765/null/null`.

is there a way to make them optional and ignore if they are null?

**Comment by lejard-h** [comment]
I assume it should behave as follow ?
```dart
getTopicContent(topicId: 1) => /topic/1
getTopicContent(topicId: 1, category: 'foo') => /topic/1/foo
getTopicContent(topicId: 1, searchQuery: 'bar') => /topic/1/bar
getTopicContent(topicId: 1, category: 'foo', searchQuery: 'bar') => /topic/1/foo/bar
```

**Comment by ksmsk** [comment]
optional paths should be chained i guess. if `category` is null then `getTopicContent(topicId: 1, searchQuery: 'bar')` should go as `/topic/1`. that would make it more clear. i tried to do something but i am relatively new to dart and code generation stuff.

**Comment by stewemetal** [comment]
IMHO calling this same function with optional parameters to basically reach multiple endpoints is kind of an antipattern. It can also lead to ambiguous usage in you upper architectural layers.

A better approach would be to define multiple methods in the API class corresponding to each kind of endpoint you have to call, for example:

```dart
@Get(path: "topic/{topicId}/{category}/{searchQuery}")
Future<Response<TopicContent>> searchTopicContent({
    @required @Path() int topicId,
    @required @Path() String category,
    @required @Path() String searchQuery,
});

@Get(path: "topic/{topicId}/{category}")
Future<Response<TopicContent>> searchTopicByCategory({
    @required @Path() int topicId,
    @required @Path() String category
});

@Get(path: "topic/{topicId}")
Future<Response<TopicContent>> getTopic({
    @required @Path() int topicId
});
```

On top of that, in Retrofit, `@Path` parameters may not be `null` at all. Passing `null` to a path parameter results in an IllegalArgumentException. This behavior should be introduced into chopper as well.

While we have the named optional parameter list syntax in Dart, it doesn't mean we have to use the parameters as optional. This will be more clear when *nullable* types will be introduced into stable Dart. When that happens, these parameters should never be allowed to be null in the first place and the code generator should fail to generate when path parameters are of nullable types. But until this utopian state of the language, we have to think a bit more on how we implement things with it. 😄

**Comment by JEuler** [comment]
I think, this is something we don't have in any REST libraries (and by a reason). And the use case is "dirty". In Retrofit on can pass empty string if the params are not needed (but this is not working in the middle of path). And we can pass empty string ("") if param wanted to be empty. 

I think this is something we don't need to implement because you should, as @stewemetal mentioned, just define methods in API class.

**Comment by JEuler** [comment]
@stewemetal @lejard-h Should we close it? :)

**Comment by stewemetal** [comment]
I vote for closing it, as it is not an issue with the library itself.

**Comment by lejard-h** [comment]
We can close indeed. It looks like a hack instead of defining a new API.
