### ISSUE TITLE
Need explanation to use it

### ISSUE THREAD

**Issue by woprandi** [lejard-h/chopper#119]
The documentation on pub.deb explains how to use chopper :
```
final chopper = ChopperClient(
    baseUrl: "http://localhost:8000",
    services: [
      // the generated service
      MyService.create()
    ],
    converter: JsonConverter(),
  );

final myService = MyService.create(chopper);

final response = await myService.getMapResource("1");

chopper.close();

```

Why instanciate 2 `MyService` instance ?

**Comment by lejard-h** [comment]
The README on pub.dev will be update on the next release.
You can follow the documentation here https://hadrien-lejard.gitbook.io/chopper/getting-started
