### ISSUE TITLE
Enabling GZip compression for Post Requests

### ISSUE THREAD

**Issue by rcpu** [lejard-h/chopper#120]
Hi,

Right now I don't find a way to enable GZip compression for post requests.

Please do let me know if this is supported and any documentation.

This is how we are using the GZIP Compression in our android native apps:
https://stackoverflow.com/questions/47637456/android-okhttp-how-to-enable-gzip-for-post?rq=1

**Comment by lejard-h** [comment]
You should be able to implements you own converter for gzip compression.

Something like that
```dart
Request compressRequest(Request request) {
  request = applyHeader(request, 'Content-Encoding', 'gzip');
  request = request.replace(body: gzip.encode(request.body));
  return request;
}

...

@FactoryConverter(request: compressRequest)
@Post()
Future<Response> postRequest(@Body() Map<String, String> data);
```

**Comment by JEuler** [comment]
Should we close this guys? :)

**Comment by JEuler** [comment]
Feel free to reopen :)
