### ISSUE TITLE
generic type in response body

### ISSUE THREAD

**Issue by P-B1101** [lejard-h/chopper#125]
when i'm trying to use generic type for response body i get error type '_$Store' is not a subtype of type 'Callback<Store>'
Callback is a class that have one generic field and few bool and string field.

Store class: 
` part 'store.g.dart';`
`abstract class Store implements Built<Store, StoreBuilder> {`
`  @nullable`
`  String get id;`
`  @nullable`
`  String get code;`
`  @nullable`
`  String get logo;`
`  @nullable`
`  String get name;`
`  Store._();`
`  factory Store([updates(StoreBuilder b)]) = _$Store;`
`  static Serializer<Store> get serializer => _$storeSerializer;`
`}`

Callback class: 

`part 'callback.g.dart';`
`abstract class Callback<E> implements Built<Callback<E>, CallbackBuilder<E>> {`
`  @nullable`
`  E get data;`
`  @nullable`
`  int get statusCode;`
`  @nullable`
`  String get message;`
`  @nullable`
`  bool get isSuccess;`
`  Callback._();`
`  factory Callback([updates(CallbackBuilder<E> b)]) = _$Callback<E>;`
`  static Serializer<Callback> get serializer => _$callbackSerializer;`
`}`

Service class: 

`part 'store_services.chopper.dart';`
`@ChopperApi()`
`abstract class StoreApiService extends ChopperService {`
`  @Get(path: RestUtils.STORE_URL)`
`  Future<Response<Callback<Store>>> getStore(@Path("code") String code);`
`  static StoreApiService create() {`
 `   final client = ChopperClient(`
  `    baseUrl: RestUtils.getBaseUrl(),`
   `   services: [`
 `       _$StoreApiService(),`
`      ],`
`      converter: BuiltValueConverter(),`
`      errorConverter: BuiltValueConverter(),`
`    );`
 `   return _$StoreApiService(client);`
 ` }`
`}`

**Comment by dhruvan2912** [comment]
I'm trying to achieve same functionality but convertResponse method not getting called

**Comment by P-B1101** [comment]
serializer class

part 'serializer.g.dart';

@SerializersFor(const [
  Users,
  Store,
  StoreCallback,
  Event,
  EventCallback,
  Discount,
  DiscountCallback,
  EventIdBody,
  Book,
  BookCallback,
  BookFilter
])
final Serializers serializers =
    (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();

converter class

import 'package:book_shop/data/rest/serializer.dart';
import 'package:built_collection/built_collection.dart';
import 'package:chopper/chopper.dart';

class BuiltValueConverter extends JsonConverter {
  @override
  Request convertRequest(Request request) {
    return super.convertRequest(request.replace(
      body: serializers.serializeWith(
          serializers.serializerForType(request.body.runtimeType),
          request.body),
    ));
  }

  @override
  Response<BodyType> convertResponse<BodyType, SingleItemType>(
      Response response) {
    final Response dynamicResponse = super.convertResponse(response);
    final BodyType customBody =
        _convertToCustomObject<SingleItemType>(dynamicResponse.body);
    return dynamicResponse.replace<BodyType>(body: customBody);
  }

  dynamic _convertToCustomObject<SingleItemType>(dynamic element) {
    if (element is SingleItemType) return element;
    if (element is List)
      return _deserializeListOf<SingleItemType>(element);
    else
      return _deserialize<SingleItemType>(element);
  }

  BuiltList<SingleItemType> _deserializeListOf<SingleItemType>(
      List dynamicList) {
    return BuiltList<SingleItemType>(
        dynamicList.map((element) => _deserialize<SingleItemType>(element)));
  }

  SingleItemType _deserialize<SingleItemType>(Map<String, dynamic> value) {
    return serializers.deserializeWith(
        serializers.serializerForType(SingleItemType), value);
  }
}
and service class is in the question

**Comment by stewemetal** [comment]
#170 seemingly fixes this issue. It was released in 3.0.6.

Closing this issue for now. Feel free to reopen if further discussion is needed. 😉
