### ISSUE TITLE
Bump pub version

### ISSUE THREAD

**Issue by krevedkokun** [lejard-h/chopper#126]
pub version still on 3.0.1+1

**Comment by JEuler** [comment]
Have you updated analyzer? Maybe you need any help with maintaining the library? :)

**Comment by fryette** [comment]
@JEuler owner ask to write email if you are ready to help maintaining

**Comment by JEuler** [comment]
Thx!

**Comment by AhmedNourJamalElDin** [comment]
I'm facing an issue while installing injectable_generator too.
> Because injectable_generator >=0.2.3 depends on analyzer ^0.39.2 and injectable_generator <0.2.3 depends on analyzer ^0.39.0, every version of injectable_generator requires analyzer ^0.39.0.

**Comment by BramDC3** [comment]
I have exactly the same issue as AhmedNourJamalElDin

**Comment by lejard-h** [comment]
Thanks for your patience, I just published the last version
chopper `3.0.2`
chopper_generator `3.0.4`
