### ISSUE TITLE
url parameter isn't actually a URL

### ISSUE THREAD

**Issue by edwardaux** [lejard-h/chopper#13]
This has always been around, but has become a bit more prominent due to the changes introduced in response to #10 which introduced a change that means `Request` now has two parameters (among others) called `baseUrl` and `url`. 

The meaning of `baseUrl` is pretty clear (to me, anyway), however, it is I feel that it is unclear what `url` means without digging into the source code. On the surface, there's no hint as to how it relates to the `baseURL` parameter? Does it replace it, do they work together, etc?

As it turns out, this parameter (also exposed via the `url` annotation) is not really a "url"... it is actually a "path" that gets appended to `baseUrl`. In fact, if you pass a fully qualified URL (eg. `'https://my.api.com/api/v1/users'`) then it still gets blindly concatenated with `baseUrl` and you end up with a malformed url (I'm just about to submit a pull request that addresses this).

Anyway, I'm not meaning to be difficult, but I think that naming of things is important. Ideally, I'd love to see this property renamed to something like `path` (or perhaps `urlSuffix`, because `baseURL` may already actually contain a partial path).

I understand this is a breaking change, but just wanted to start a discussion to see what your thoughts are.

**Comment by lejard-h** [comment]
Renaming to path does not seem to be a problem to me, I will also add more documentation.

**Comment by lejard-h** [comment]
I pushed the change in `1.2.0-dev3`

**Comment by lejard-h** [comment]
`2.0.0 released`
