### ISSUE TITLE
Unhandled Exception: Invalid argument (body)

### ISSUE THREAD

**Issue by igiagante** [lejard-h/chopper#130]
Hi, 

I've been trying to figure out why chopper lib through an exception when it does not find the body's type. Is this an issue? or am I missing sth out?

The documentation says

```@Post()
Future<Response> post(@Body() Map<String, dynamic> body);
```

Method from Serializable Class to be used
```
Map<String, dynamic> toJson() => _$CreateChallengeCommentDTOToJson(this);
```

After doing this post

```
@Post(path: '/challenge-comment/')
Future<Response> createChallengeComment(@Body() Map<String, dynamic> body);

await _challengeApi.createChallengeComment(challengeComment.toJson());
```

I get this error

**Unhandled Exception: Invalid argument (body): "{text: testsetsetes, author: 5e42f40976ad3400248c5df6, challenge: 5e236400f6ed05f919b217e9}"**

<img width="455" alt="Screen Shot 2020-04-02 at 12 05 42 PM" src="https://user-images.githubusercontent.com/3419609/78265822-5753f000-74db-11ea-95ef-aa478c2da0ff.png">

After reading the method **toHttpRequest**, I'm wondering why it tries to check if the body is Map<String, String> when it's supposed to receive Map<String, dynamic>.

To avoid this issue, I have to convert it explicitly:

```
Map<String, String> body = {};

challengeComment.toJson().forEach((key, value) {
      body[key] = value;
    });
```

**Comment by Moyck** [comment]
I have the same problem

**Comment by Moyck** [comment]
Oh,When I used  JsonConverter, the problem disappeared

_chopperClient = ChopperClient(
      converter: JsonConverter(),
        ...
    );

**Comment by JEuler** [comment]
@igiagante It seems that this was converter problem on client code? Closing it, feel free to reopen if needed.
