### ISSUE TITLE
how to  use public key pinning?

### ISSUE THREAD

**Issue by MangeshKadam** [lejard-h/chopper#131]

**Comment by JEuler** [comment]
Is that this thing? https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning
Isn't it deprecated?

**Comment by MangeshKadam** [comment]
so we used public key pinning in native android projects. Thanks for informing this is deprecated. I wanted to achieve the same in flutter project. Any other alternative to avoid man in the middle attack will be good. Does chopper provides any mechanism for the same?

**Comment by JEuler** [comment]
Hm, I don't have experience with that, maybe @stewemetal @lejard-h have.
As I understand, https://github.com/dart-lang/sdk/issues/35981 - this is the thing you can use for pinning, https://github.com/dart-lang/sdk/issues/35981#issuecomment-535729786

**Comment by nioncode** [comment]
@JEuler HPKP is not the same as simply pinning the public key in an app – which is not deprecated at all –, but refers to the method of pinning the public key through an HTTP header.

**Comment by JEuler** [comment]
@nioncode Thank you for the information!

**Comment by MangeshKadam** [comment]
do we have any solution?

**Comment by nioncode** [comment]
@techouse can you show an example how this can be done, since you closed it as completed?

**Comment by techouse** [comment]
@nioncode use https://pub.dev/packages/certificate_pinning_httpclient as your `Client`.
