### ISSUE TITLE
 Could not find the correct Provider<ApiService> above this Widget

### ISSUE THREAD

**Issue by OlalKeith** [lejard-h/chopper#136]
HI , I have two services , ApiService and PostApiService. One using BuiltValueConverter() and the other JsonConverter(). 
```

static ApiService create() {
  final client = ChopperClient(
    baseUrl: baseUrlStr,
    services: [
      _$ApiService(),
    ],
    converter: BuiltValueConverter(),<----------- //The difference is here:
    interceptors: [HttpLoggingInterceptor()],
  );
  return _$ApiService(client);
}
---------------------------------------------------------------------------------------------------------------------------------------
static PostApiService create() {
  final client = ChopperClient(
    baseUrl: baseUrlStr,
    services: [
      _$PostApiService(),
    ],
    converter: JsonConverter(),<----------- //The difference is here:
    interceptors: [HttpLoggingInterceptor()],
  );
  return _$PostApiService(client);
}
```

Is it possible to have two chopper services without getting this error:

Error: Could not find the correct Provider<ApiService> above this Widget

To fix, please:

  * Ensure the Provider<ApiService> is an ancestor to this Widget
  * Provide types to Provider<ApiService>
  * Provide types to Consumer<ApiService>
  * Provide types to Provider.of<ApiService>()
  * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
  * Ensure the correct `context` is being used.

**Comment by JEuler** [comment]
@OlalKeith Why you have closed this?All is okay?

**Comment by OlalKeith** [comment]
Hello ,
The error was in my part.  I had not listed one of my services in the list of provider in the main.dart file.

**Comment by JEuler** [comment]
Okay, thanks!
