### ISSUE TITLE
Return generic type from Get request

### ISSUE THREAD

**Issue by SandroMaglione** [lejard-h/chopper#137]
I would like to specify a generic type for the return value of a get request.
Currently, when I add the generic `<T>` the generated code does not compile.
```dart
  @Get(path: '{path}')
  Future<Response<BuiltList<User<T>>>> getProfile<T>(
      @Path() String path, @Query() String idUser);
```
results in:
```dart
  @override
  Future<Response<BuiltList<User<T>>>> getProfile(String path, String idUser) {
    final $url = '$path';
    final $params = <String, dynamic>{'idUser': idUser};
    final $request = Request('GET', $url, client.baseUrl, parameters: $params);
    return client
        .send<BuiltList<User<T>>, User<T>>($request);
  }
```
which does not compile because it does not recognize the type `T` (it should be `Future<Response<BuiltList<User<T>>>> getProfile<T>(String path, String idUser)`).

How could I solve this?

**Comment by JEuler** [comment]
Hm, I will investigate this on weekends, but as a thought - why are you need this feature? The main purpose of Chopper / Retrofit guys are to provide the TYPED way of handling the data coming from web.

**Comment by SandroMaglione** [comment]
In my use-case, I have a model that contains the history of data, with a list of objects each having the `DateTime` in which the data has been collected and a value. The value can have different types but the history is treated the same, therefore I use a genetic type `T` for the value.

The request should return `DateTime` and value, with the value which is different based on the generic `T`.

**Comment by JEuler** [comment]
So, your API returning different (dynamic) values from one route? Am I correct?

**Comment by SandroMaglione** [comment]
Yes, currently I have one REST endpoint that returns `int`, `double`, or `String` based on the requested resource.

**Comment by stewemetal** [comment]
Do you have any control over that endpoint? It's kind of an antipattern, so if you _do_ have control over it, try to make it more predictable (I mean type safe 😄 ).

However, if you can't modify the endpoint, you could implement a type converter that parses the response the way you like. Maybe you could output a type (class) that has a dynamic property and wrap your received value with it. This is just my first thought, it may not be even possible at the moment. Just a hunch. :)

**Comment by JEuler** [comment]
Maybe you should as @stewemetal mentioned (kind of) just create class with DateTime field and dynamic field and then just convert the value by type casting?

**Comment by SandroMaglione** [comment]
I actually did not know that it is considered an antipattern 😅 
I thought I could simplify the architecture but I see also some problems that it might generate in the future. Luckily, I do have control over the API so I can fix it. 

As a general thought, I do not personally like assigning type `dynamic` to any variable, I see it as confusing and error-prone. 
I do not know if it still may be a feature to consider adding to the package. Thanks for your suggestions 👍

**Comment by stewemetal** [comment]
Actually, using the `dynamic` "type" should be avoided whenever it's possible. It just switches off all and any type safety IDEs, and more importantly developers, can rely on. Chopper itself aims to be as type safe as possible. 😄   

I'm closing this issue now, but feel free to reopen it any time!
