### ISSUE TITLE
Send Request as FormData 

### ISSUE THREAD

**Issue by arpitt1692** [lejard-h/chopper#138]
```dart
@ChopperApi(baseUrl: 'http://192.168.1.20/bindal/api/v1/user/')
abstract class ApiService extends ChopperService {

  @Post(path: "login",headers: {"Content-Type": "application/x-www-form-urlencoded"})
  Future<Response<LoginResponse>> doLogin([
    @Header('auth_key') String authType,
    @Query('email') String email,
    @Query('password') String password,
    @Query('userType') String userType,
  ]);

  static ApiService create() {
    final client = ChopperClient(
      // The first part of the URL is now here
      baseUrl: 'http://192.168.1.20/bindal/api/v1/user/',
      services: [
        // The generated implementation
        _$ApiService(),
      ],
      interceptors: [
        HttpLoggingInterceptor()
      ],
      // Converts data to & from JSON and adds the application/json header.
      converter: JsonConverter(),
    );

    // The generated class with the ChopperClient passed in
    return _$ApiService(client);
  }
}
```

is this the correct way to send request as FormData

**Comment by SewerynKubica-GrupaPracuj** [comment]
I found this in annotations.dart from Chopper code.
Might be usefoul

`/// Defines a field for a `x-www-form-urlencoded` request.
/// Automatically binds to the name of the method parameter.
///
/// ```dart
/// @Post(path: '/')
/// Future<Response> create(@Field() String name);
/// ```
/// Will be converted to `{ 'name': value }`.
@immutable
class Field {
  /// Name can be use to specify the name of the field
  /// ```dart
  /// @Post(path: '/')
  /// Future<Response> create(@Field('id') String myId);
  /// ```
  final String? name;

  const Field([this.name]);
}`
