### ISSUE TITLE
Update built_value and built_value_generator packages

### ISSUE THREAD

**Issue by abhaysood** [lejard-h/chopper#140]
The latest `built_value` package version is  ^7.1.0. The `chopper_built_value` package is on ^6.7.1.

Are there any known issues in updating this dependency?  If not I can help by sending a PR.

**Comment by stewemetal** [comment]
That would be a major version upgrade which is kind of risky, but fortunately we have tests for `built_value`. :)

We would really appreciate your help on this! 👍

**Comment by JEuler** [comment]
https://github.com/lejard-h/chopper/pull/142 on it :)

**Comment by JEuler** [comment]
Hi! If you are still interested, the https://github.com/lejard-h/chopper/pull/142 was merged, now we will need to release new version on pub dart (with the help of our FATHER CREATOR @lejard-h) and all is okay.

**Comment by JEuler** [comment]
@abhaysood Are you good with closing this issue?

**Comment by abhaysood** [comment]
Yes, thanks for getting this done! 👍
