### ISSUE TITLE
Chopper return 20 items only

### ISSUE THREAD

**Issue by tony123S** [lejard-h/chopper#143]
I have more than 20 items in server, but chopper only retrieve 20 items. 

It requires us to pass [Query parameters](https://hadrien-lejard.gitbook.io/chopper/requests#query-parameters) ?

**Comment by JEuler** [comment]
What do you mean? Chopper is not restricting you in that case. If you have endpoint on backend side which is using some kind of pagination - yeah, you probably should use query parameters.

**Comment by tony123S** [comment]
I use postman to test, the server return more than 20 items. But if I use Chopper, it only return 20.

**Comment by tony123S** [comment]
sorry, my bad.
