### ISSUE TITLE
Custom Reqeust parameters for url format

### ISSUE THREAD

**Issue by jiechic** [lejard-h/chopper#148]
i want to use Customer DateTime format in request parameters
```
@Get(path: "noticeRead/list")
  Future<Response<NoticeList>> noticeList(
      @Query("afterTime") DateTime afterTime);
```
in default afterTime will print use afterTime.toString
`2020-06-22 T12:32.00.000Z`

I wan global cutomer use DateFormat.format(afterTime)
`2020-06-22 12:32.00`

can chopper add custom converter for build uri to output custom object format?

**Comment by jiechic** [comment]
i want to use Converter to conver parameters but in source 
`Future<Request> _handleRequestConverter(
    Request request,
    ConvertRequest requestConverter,
  ) async {
    if (request.body != null || request.parts.isNotEmpty) {
      if (requestConverter != null) {
        request = await requestConverter(request);
      } else {
        request = await _encodeRequest(request);
      }
    }

    return request;
  }`
it‘s jump out fun _encodeRequest，
I did not change query paramter on Converter

**Comment by JEuler** [comment]
You can change the `@Query("afterTime") DateTime afterTime)` param to be String and manually convert it in client code, without relying on `toString` conversion. 

As I understand your problem. :)

**Comment by jiechic** [comment]
> You can change the `@Query("afterTime") DateTime afterTime)` param to be String and manually convert it in client code, without relying on `toString` conversion.
> 
> As I understand your problem. :)

Actually
In my project group, the interaction time with the service must specify GTM+8. If this code is written between the repository and chopper, there will be one more code conversion DateFotmat.format(datetime)
However, as long as it is written by people, there will be times when they forget
Therefore, using local datetime to pass in the app, and time zone conversion in the conver of the network layer is a good way to avoid human forgetting. We also use the query converter of okhttp to do it.

some special objects can be customized by building a converter by themselves, and some special type parameters can be customized, and then converted into the desired look through the converter.

you can see 
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Converter.java
`/**
     * Returns a {@link Converter} for converting {@code type} to a {@link String}, or null if
     * {@code type} cannot be handled by this factory. This is used to create converters for types
     * specified by {@link Field @Field}, {@link FieldMap @FieldMap} values, {@link Header @Header},
     * {@link HeaderMap @HeaderMap}, {@link Path @Path}, {@link Query @Query}, and {@link
     * QueryMap @QueryMap} values.
     */
    public @Nullable Converter<?, String> stringConverter(
        Type type, Annotation[] annotations, Retrofit retrofit) {
      return null;
    }`

**Comment by JEuler** [comment]
But you can put the conversion into the entity that is processing network request, repository, service, store, whatever. 

Also, have you tried using the Interceptor? (maybe not good for this situation) 
```dart
(Request request) async =>
              request.copyWith(
                      body: YOURNEEDEDBODY)
```

Or the Converter like that (if you are extending `JsonConverter`):
```dart
return super.convertRequest(request.copyWith(
        body: processedBody,
      )),
```

**Comment by jiechic** [comment]
> Also, have you tried using the Interceptor? (maybe not good for this situation)

thanks for your reminder

i saw chopper source
that _interceptRequest run before request.toBaseRequest()._buildUri()
it can work in my requirement

in first i use extending  Converter,
it is not run converter in function _handleRequestConverter because  http.get don't have  request body
