### ISSUE TITLE
Support http.MultiPartFile type with @PartFile annotation

### ISSUE THREAD

**Issue by stewemetal** [lejard-h/chopper#150]
Based on this SO question:

https://stackoverflow.com/questions/59791332/upload-image-with-chopper

We might not be able to do it, but it would be a good improvement to support a type made for this, and not just Strings. :)

Research needed.

**Comment by erlangparasu** [comment]
any update?

**Comment by techouse** [comment]
> any update?

This is [already covered](https://github.com/lejard-h/chopper/blob/master/chopper/lib/src/annotations.dart#L424)
