### ISSUE TITLE
upload image using binary body

### ISSUE THREAD

**Issue by jiechic** [lejard-h/chopper#152]
![image](https://user-images.githubusercontent.com/518977/87137495-93af9d00-c2cf-11ea-9bc2-4713d1cdf49c.png)
`@ChopperApi()
abstract class FileApi extends ChopperService {
  static FileApi create([ChopperClient client]) => _$FileApi(client);

  @Put(path: '/{path}')
  Future<Response<FileInfo>> fileUpload(
      @Path('path') String path,
     
       String filePath);
}`
How to define filePath

**Comment by JEuler** [comment]
Hi, so what is your question? You need to send binary file, like image yeah? 
https://stackoverflow.com/questions/59988978/how-to-send-file-using-chopper - here you go

**Comment by JEuler** [comment]
But this is Multipart (in your link):
```dart
static Future<bool> uploadPhoto(String url,  Uint8List photo) async {
  Response res = await Dio().put(url,
      data: MultipartFile.fromBytes(photo).finalize(), options: Options(headers: {“Content-Type”: “image/jpeg”}));
  if (res.statusCode == 200)
    return true;
  else
    return false;
}
```

You can use something like that in Chopper. Have a look here https://stackoverflow.com/questions/60752434/flutter-chopper-file-upload-api-throw-nosuchmethoderror
