### ISSUE TITLE
Can't pub get chopper library pubspec file？

### ISSUE THREAD

**Issue by huajianjiang** [lejard-h/chopper#155]
When I run pub get in chopper/chopper dict , why it always redirect to chopper/chopper/example to find pubspec?

![console](https://user-images.githubusercontent.com/12984573/88877809-f655e200-d258-11ea-89d6-748944b5de01.png)
![catelog](https://user-images.githubusercontent.com/12984573/88877820-0077e080-d259-11ea-83a5-c104b0ec0f8b.png)

**Comment by stewemetal** [comment]
I'm closing this issue as it appears to be inactive.

Feel free to reopen it if further discussion is needed. 😉
