### ISSUE TITLE
Set content-type when using @PartFile

### ISSUE THREAD

**Issue by Danaru87** [lejard-h/chopper#161]
I need to upload images via Chopper.

I use @PartFile() but i can't specify the content type for this part.

My server receive a part with content-type: application/octet-stream, i want to specify it's a image/png or image/jpeg.

```dart
@Post(headers: {"Content-Type": "multipart/form-data"})
@multipart
Future<Response> sendImage(
      @PartFile('image') String imagePath);
```
How to do it using chopper ?

I'm using http library to do what i want :/

I think, something like this can be very usefull:

```dart
@PartFile('image', contentType: "image/jpeg")
```

**Comment by Danaru87** [comment]
> @Danaru87 Also, take a look at this comment:
> [#55 (comment)](https://github.com/lejard-h/chopper/issues/55#issuecomment-575107144)

Thx ;)

**Comment by JEuler** [comment]
@Danaru87 Does it help? Can this issue can be closed? :)

**Comment by Danaru87** [comment]
@JEuler  yes ! Sorry ;)
