### ISSUE TITLE
How I can remove "charset=utf-8" from header "content-type: application/json" ?

### ISSUE THREAD

**Issue by pierrediderot** [lejard-h/chopper#162]
Could someone help me, remove the "charset=utf-8" encoding from the Content-Type header.

Example:
POST /api/restaurant/nearby HTTP/1.1
user-agent: Dart/2.8 (dart:io)
content-type: application/json; **charset=utf-8** _I want remove this._
accept-encoding: gzip
content-length: 235
host: 192.168.10.2:7777

**Comment by dutsky** [comment]
did you solve this issue? How? I'm trying to use `@Header` annotation from this https://github.com/lejard-h/chopper/issues/89 , but it's don't overwrite content-type header unfortunately.

**Comment by crozarakamilla** [comment]
Still having the same problem even after using @Headers and HeaderInterceptor.

**Comment by ltropin** [comment]
It's problem by package [http](https://pub.dev/packages/http).

After Chopper set body for Request (from HTTP package) (see screenshot)

![image](https://user-images.githubusercontent.com/43740557/158623712-323ba79b-0ae5-479c-a2a9-96661575c52b.png)

body setter change header

![image](https://user-images.githubusercontent.com/43740557/158624191-44a1170d-be10-45f7-bd76-d222f8191be6.png)

The only solution you can do is add interceptor.
