### ISSUE TITLE
Charles Proxy

### ISSUE THREAD

**Issue by locskot** [lejard-h/chopper#163]
I faced a problem with proxying requests
 var httpClient = HttpClient();
    httpClient.idleTimeout = const Duration(seconds: 5);
    httpClient.findProxy = (uri) => "PROXY 192.168.1.71:8888";

var ioClient = http.IOClient(httpClient);

final client = ChopperClient(
      client: ioClient,
      baseUrl: BASE_URL,
      services: [
        _$IwayApi(),
      ],
      interceptors: [
        HttpLoggingInterceptor(),
        CurlInterceptor(),
        AuthorizationInterceptor(),
      ],
      converter: JsonConverter(),
    );

    return _$IwayApi(client);

I can not understand why I received this error
SocketException: OS Error: Connection refused, errno = 61, address = 192.168.1.71, port = 54076

**Comment by stewemetal** [comment]
@locskot @JEuler Indeed, this seems to be a http error, or something not correctly set up in your proxy configuration. Without knowing your network configuration, it's hard to tell what the problem might be.

I'm closing this issue as it's not related to Chopper itself.

@locskot please feel free to reopen the issue any time!
