### ISSUE TITLE
How to check for exception in chopper

### ISSUE THREAD

**Issue by jesseframework** [lejard-h/chopper#168]
Hello how do i check for exception in chopper using dart. Example no internet or issues with url. I also want to know how to queue http request in chapper if the internet is down and retry when connection is restored.

**Comment by JEuler** [comment]
So, you can just use `try` `on` on your network queries. 
Or, if you want to setup global handling - just use the response interceptor like this:
```dart
if (response.statusCode == 504) {
              UiHelper.toastShow(translate('timeoutError'));
            }
```

About retry: https://github.com/lejard-h/chopper/issues/47

**Comment by stewemetal** [comment]
For a more robust "retry" mechanism, have a look at the [workmanager](https://pub.dev/packages/workmanager) package. The only downside is it is really more for Android (and more or less for iOS).

**Comment by stewemetal** [comment]
I'm closing this issue.

Feel free to reopen if further discussion is needed. 😉
