### ISSUE TITLE
Support @PartMap like Android Retrofit

### ISSUE THREAD

**Issue by minhbnt-1512** [lejard-h/chopper#169]
What is the same as @PartMap in Chopper?
https://square.github.io/retrofit/2.x/retrofit/index.html?retrofit2/http/PartMap.html

**Comment by Jparrgam** [comment]
@BaloghTamas @lejard-h hi, 🔝  will he ever get support from this?

**Comment by BaloghTamas** [comment]
I don't think chopper supports this exactly, I mean to provide a map of parts. Right now only the [Part](https://github.com/lejard-h/chopper/blob/develop/chopper/lib/src/annotations.dart#L319) annotation is supported, which lets you pass predefined parts, so the number and the name of the parts are defined at generation time.
