### ISSUE TITLE
License required.

### ISSUE THREAD

**Issue by kiruto** [lejard-h/chopper#17]
[Chopper in Dart packages](https://pub.dartlang.org/packages/chopper) shows that Chopper using a MIT based license.
Could you please add a LICENSE file to this repo?
Thanks.

**Comment by lejard-h** [comment]
the LICENSE file is available for each packages

https://github.com/lejard-h/chopper/blob/master/chopper/LICENSE
https://github.com/lejard-h/chopper/blob/master/chopper_generator/LICENSE
