### ISSUE TITLE
cache http response

### ISSUE THREAD

**Issue by MahdiPishguy** [lejard-h/chopper#171]
in my mobile application i'm using [Chopper][1] `http` library and i would like to cache http response with this library, my server return this headers with responses:

    <-- 200 http://www.www.www/api/v1/dashboard/allData
    content-type: application/json
    cache-control: max-age=600, private
    transfer-encoding: chunked
    date: Mon, 07 Sep 2020 05:47:00 GMT
    server: Apache

i added this interceptor to `chopper` interceptors:

```dart
@ChopperApi(baseUrl: '/api/v1')
abstract class WebApi extends ChopperService {
  @Get(path: '/dashboard/allData')
  Future<Response> getDashboardItems();

  static WebApi create() {
    final client = ChopperClient(
        client: http.IOClient(
          HttpClient()..connectionTimeout = const Duration(seconds: 60),
        ),
        baseUrl: webUri,
        services: [
          _$WebApi(),
        ],
        converter: const JsonConverter(),
        interceptors: [
          const HeadersInterceptor({'Content-Type': 'application/json','Cache-Control':'private, max-age=600'}),
          HttpLoggingInterceptor(),
        ]);
    return _$WebApi(client);
  }
}
```

now i expect cache work fine for my application, this solution is correct?

  [1]: https://pub.dev/packages/chopper

**Comment by stewemetal** [comment]
I'm closing this issue. Please feel free to reopen it if you have any more questions. :)
