### ISSUE TITLE
typedef ConvertRequest and typedef ConvertResponse

### ISSUE THREAD

**Issue by Study-Log** [lejard-h/chopper#174]
# Current implementation

```dart
typedef ConvertRequest = Request Function(Request request);
typedef ConvertResponse<T> = Response Function(Response response);
```

# Suggestion

```dart
typedef ConvertRequest = FutureOr<Request> Function(Request request);
typedef ConvertResponse<T> = FutureOr<Response> Function(Response response);
```

A routine for the conversion is already implemented as an `async` and all of the conversion function is already being `await`ed. 
And also `Converter` class is using `async` methods for the conversion. So it will be great to change the `typedef` to the suggestion.

**Comment by JEuler** [comment]
Merged, thanks!
