### ISSUE TITLE
Is it possible to have multiple baseUrl in Chopper client?

### ISSUE THREAD

**Issue by tony123S** [lejard-h/chopper#176]
Is it possible to have multiple baseUrl in Chopper client?

**Comment by JEuler** [comment]
You can just use the AppConfig concept for this thing. If I properly understand you.

**Comment by JEuler** [comment]
https://gist.github.com/nicowernli/b776104e9c58da4b267ba0ab299a6b15

**Comment by tony123S** [comment]
Thanks but sorry I can't get you.

Currently I have this code. I would like to have second base url. Do I need to create a separate client and service? 

class ABCClient {
  final ChopperClient chopperClient;
 static const String BASE_URL = "https://url_one.com/xxx/";
 
  ABCClient()
      : chopperClient = ChopperClient(
            baseUrl: BASE_URL,
            services: [Service.create()],
            interceptors: [HttpLoggingInterceptor()],
            converter: JsonConverter()) {
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
  }

**Comment by JEuler** [comment]
What do you mean by multiple baseUrl? Per flavor? Per build? In runtime? If in the runtime - you'll need separate client for this. 

But if you do this to separate your testing environment from production, e.g. qa.api.com vs prod.api.com you can inject base URL using the AppConfig mechanism and create special build configuration. If it is your case, I can help you with some examples, I'm doing it in my work project.

**Comment by JEuler** [comment]
Also, you can https://github.com/lejard-h/chopper/blob/develop/faq.md#runtime-baseurl-change change baseUrl in the runtime like this. But as I understand, you need TWO+ baseUrl at the same time, so, I think you should go with separate clients.

**Comment by JEuler** [comment]
Closing, feel free to reopen.
