### ISSUE TITLE
update analyzer dependency

### ISSUE THREAD

**Issue by boskokg** [lejard-h/chopper#177]
Because chopper_generator 3.0.5 depends on analyzer ^0.39.8 and no versions of chopper_generator match >3.0.5 <4.0.0, chopper_generator ^3.0.5 requires analyzer ^0.39.8.

Workaround is to use dependency_overrides...

**Comment by JEuler** [comment]
@boskokg Hm, I'm facing a bug with generation when I'm using this workaround. Need to recheck on new analyzer.

**Comment by NikitaMasev** [comment]
The same problem.

**Comment by PalakSDarji** [comment]
Any fixes so far?

**Comment by JEuler** [comment]
Yesterday we have deployed fix(https://github.com/lejard-h/chopper/pull/178), so, need to decide about release procedure. 
 
@stewemetal @lejard-h

**Comment by JEuler** [comment]
Released, so, closing
