### ISSUE TITLE
It may better that move JSON/FormEncoded logics from client to Converter.

### ISSUE THREAD

**Issue by kiruto** [lejard-h/chopper#18]
Hi lejard-h,

For base.dart and request.dart, I think it may better that move the code bellow into Converter implementations.

```dart
/// in base.dart
final bool jsonApi;
final bool formUrlEncodedApi;

/// in request.dart
final bool multipart;
final bool json;
```

By doing those, it'll be easier to implement the multiple converter within a single client instance.

**Comment by kiruto** [comment]
For example, in Retrofit, GSON converter factory is implemented like [this](https://github.com/square/retrofit/blob/c1b100f3c4e84711fa23bdfed03cb78c4d8a8f19/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonRequestBodyConverter.java).

**Comment by kiruto** [comment]
I suggest that create some annotations like "ChopperJson" and "ChopperJsonFactory", which decorate the object class and it's static factory function.
In generator, add all the functions marked with "ChopperJsonFactory" in a Type-ObjectFactor map in same file, and create class wraps this map, so user can create the instance of the wrapper class, and add it into chopper client.

**Comment by lejard-h** [comment]
`2.0.0 released`

- ChopperClient.jsonApi deprecated, use a JsonConverter instead
- ChopperClient.formUrlEncodedApi, use FormUrlEncodedConverter instead
- remove JsonEncoded annotation, use FactoryConverter instead
