### ISSUE TITLE
Changelog file

### ISSUE THREAD

**Issue by danielgomezrico** [lejard-h/chopper#186]
Is there any changelog file?

Im asking because I see a version `3.0.6` but it is not in the releases or the https://pub.dev/packages/chopper/changelog so I dont get what was released.

**Comment by Purvik** [comment]
Hey, @lejard-h  We really appreciate updated versions for this package but we would like to know changes that are being done in change log so we can have a good track of it while updating to latest version.

**Comment by stewemetal** [comment]
I'm planning to facilitate proper changelogs starting with 3.0.7. Thanks for your patience. 😉
