### ISSUE TITLE
Converting JSON response to Model Object using Chopper library in flutter?

### ISSUE THREAD

**Issue by CherukuriSiva** [lejard-h/chopper#187]
I am using the Chopper library to invoke rest API calls.

I have followed the Raywenderlich Chopper Tutorial tutorial to implement API calls in my project.
[https://www.raywenderlich.com/10099546-elegant-networking-in-flutter-with-chopper](https://www.raywenderlich.com/10099546-elegant-networking-in-flutter-with-chopper)

In this tutorial, they have used the below code to convert JSON response to the Popular model object.

    try {
      var mapData = json.decode(body);
      var popular = Popular.fromJson(mapData);
      return response.copyWith<BodyType>(body: popular as BodyType);
    } catch (e) {
      chopperLogger.warning(e);
      return response.copyWith<BodyType>(body: body);
    }
This is fine. But in my project, I have to make multiple API calls and need to decode multiple JSON responses to Dart model objects.

So how to decode multiple API calls responses? Do I need to do something like below:

```
import 'dart:convert';
import 'package:chopper/chopper.dart';

class ModelConverter implements Converter {
  @override
  Request convertRequest(Request request) {
    final req = applyHeader(
      request,
      contentTypeKey,
      jsonHeaders,
      override: false,
    );

    return encodeJson(req);
  }

  Request encodeJson(Request request) {
    var contentType = request.headers[contentTypeKey];
    if (contentType != null && contentType.contains(jsonHeaders)) {
      return request.copyWith(body: json.encode(request.body));
    }
    return request;
  }

  Response<BodyType> decodeJson<BodyType, InnerType>(Response response) {

    var contentType = response.headers[contentTypeKey];
    var body = response.body;
    if (contentType != null && contentType.contains(jsonHeaders)) {
      body = utf8.decode(response.bodyBytes);
    }
    try {
      var mapData = json.decode(body);

      if(mapData['popularResponse'] != null) {
        Popular popularResponse = Popular.fromJson(mapData);
        return response.copyWith<BodyType>(
                  body: popularResponse as BodyType);
      } else if(mapData['articleResponse'] != null) {
        Article articleResponse = Article.fromJson(mapData);
        return response.copyWith<BodyType>(
                  body: articleResponse as BodyType);

      } else if(......) {
        ......
      }

    } catch (e) {
      chopperLogger.warning(e);
      return response.copyWith<BodyType>(body: body);
    }
  }

  @override
  Response<BodyType> convertResponse<BodyType, InnerType>(Response response) {
    return decodeJson<BodyType, InnerType>(response);
  }
}
```
How to proceed further?

**Comment by grahamsmith** [comment]
My example here might be of use @CherukuriSiva - https://github.com/lejard-h/chopper/issues/199#issuecomment-770369596

**Comment by Isuru-Nanayakkara** [comment]
I'm also having this issue. @CherukuriSiva Were you able to resolve this?
