### ISSUE TITLE
override a baseUrl for a Request Method

### ISSUE THREAD

**Issue by DAMMAK** [lejard-h/chopper#195]
if I want to use a different baseUrl for a httpMethod e.g @Get(), @Post().... I should be able to override the baseUrl for that specific request.

e.g 

@Get(baseUrl: "github.com", path: "/profile")
 Future<Response> getProfile();

**Comment by stewemetal** [comment]
You should be able to do this by passing a full http/https URL as the `path`.

For example:

```dart
@get(path: "https://github.com/profile")
Future getProfile();
```

`Request`s ignore the `ChopperClient`'s `baseUrl if the URL starts with _http://_ or _https://_ [as you can see here](https://github.com/lejard-h/chopper/blob/73dc1723150df55d3c5ba90658993f776dea13cf/chopper/lib/src/request.dart#L159).

This behavior is yet to be documented. I'll label this issue for documentation improvement.

**Comment by stewemetal** [comment]
@DAMMAK Have a look at [e335972](https://github.com/lejard-h/chopper/commit/e335972a1eedc84ac7a01a97d62f28367cfe079b) for a detailed behavior of how URLs are generated for requests. :wink: The description will be a part of the 3.0.7 release.

I'm closing this issue for now. Feel free to reopen it if you have further questions.
