### ISSUE TITLE
Generic response type

### ISSUE THREAD

**Issue by dgulmez** [lejard-h/chopper#199]
I am trying to use chopper with built value technique to call existing REST api methods.
This api is currently in use and it is not going to be an easy process to change all the clients using it.

Rest api was designed to return a response like this for all methods:

```
class WebRespone
{
	bool HasErrors;
	string Message;
	object ReturnValue;
}

```
Different methods return certain type as ReturnValue and it is well documented in api document.
For example

/api/logon method returns a WebResponse with "`User`" type as ReturnValue
or /api/getUsers method returns a WebResponse with "`List<User>`" as ReturnValue
so on.

This is what I tried so far:

I registered a logon service as follows,

```
  Future<Response<WebRespone<User>>> logon(
      [@Header('Username') String username,
      @Header('Password') String password]);
```

I also created following classes:

```
abstract class WebResponse<T>
    implements Built<WebResponse<T>, WebResponseBuilder<T>> {
  @nullable
  @BuiltValueField(wireName: "ReturnValue")
  T get returnValue;

  @nullable
  @BuiltValueField(wireName: "Message")
  String get message;

  @BuiltValueField(wireName: "HasErrors")
  bool get hasErrors;

  WebResponse._();

  factory WebResponse([Function(WebResponseBuilder<T>) updates]) =
      _$WebResponset<T>;

  static Serializer<WebResponse> get serializer =>
      _$webResponseSerializer;
}
```

```
abstract class User implements Built<User, UserBuilder> {
  @BuiltValueField(wireName: "ID")
  String get id;
  @BuiltValueField(wireName: "UserName")
  String get userName;

  User._();

  factory User([updates(UserBuilder b)]) = _$User;

  static Serializer<User> get serializer => _$userSerializer;
}
```

Serializer Built classes are successfully generated  and i am able to receive a response.

However a runtime error is thrown when response is being tried to deserialize.

The error message is:

DeserializationError (Deserializing '[ReturnValue, {ID: 094ae423-f5a3-4911-aa17-b54f309972c2, UserName: test12, ...' to 'User' failed due to: Tried to construct class "User" with null field "id". This is forbidden; to allow it, mark "id" with @nullable.)

As you can see, ID column is not null. After digging into the code a little bit, I realized that deseralize method actually is trying to deserialize the whole WebResponse as a User. 

First of all I wonder if Chopper supports this kind of Generic responses (when using built value technique)

If it does, am I missing something in my code?

**Comment by grahamsmith** [comment]
I also had this problem and found BuiltValue was harder to implement (although I plan to see if Freezed will have the same issues)

My solution is:

```
class ApiResponse {

  final ApiResponseStatus status;

  ApiResponse(this.status);
}
```

The above represents the "envelope" for each response from the API. Notice is does *NOT* have any serialisation attributes.

Next my response status class does have serialisation attributes:

```
@JsonSerializable(nullable: false)
class ApiResponseStatus {

  @JsonKey(name: 'status_message', nullable: true)
  final String message;

  ApiResponseStatus(this.message);

  factory ApiResponseStatus.fromJson(Map<String, dynamic> json) => _$ApiResponseStatusFromJson(json);

  Map<String, dynamic> toJson() => _$ApiResponseStatusToJson(this);
}
```

Finally putting it all together when I create a class to model the API response:

```
@JsonSerializable()
class Foo extends ApiResponse {

  @JsonKey(name: 'data')
  Bar data;

  Foo({ApiResponseStatus status, this.data}) : super(status);

  static const fromJsonFactory = _$FooFromJson; //this is used by the ChopperClient

  factory Foo.fromJson(Map<String, dynamic> json) => _$FooFromJson(json);

  Map<String, dynamic> toJson() => _$FooToJson(this);
}
```

Note how I pass in the status in the constructor of `Foo`. I do not like this too much but it was the smallest boilerplate version of this I could get working in a reasonable amount of time.

When I create my ChopperClient I pass a converter that uses the `fromJsonFactory` method to perform the deserialisation. I'm thinking of writing some code gen that does this wiring for me but in the meantime it looks like this:

```
static ChopperClient create({String baseUrl, List<dynamic> interceptors}) {

    final converter = JsonSerializableConverter({
      RequestOtpResponse: RequestOtpResponse.fromJsonFactory,
      SignInResponse: SignInResponse.fromJsonFactory,
    });

    return ChopperClient(
      baseUrl: baseUrl,
      converter: converter,
      interceptors: interceptors,
    );
  }
```

**Comment by stewemetal** [comment]
From my point of view (and definitely correct me if I'm wrong!), you have the case of wrapped network responses.

Having a single `WebResponse` class that is decoded based on which network call returns it seems too much of an abstraction and it may not be the solution you should go with.

You pretty much have a well-defined REST API ("Different methods return certain type as ReturnValue"). What's wrong with defining XResponse (like `LogonResponse`, `UsersResponse`) classes for each call? Yes, it's more code, but less abstraction.

I'm thinking of classes like these:

```dart
class LogonResponse {
	bool HasErrors;
	string Message;
	User user;
}

class UsersResponse {
	bool HasErrors;
	string Message;
	List<User> user;
}
```

I've encountered such unfortunate backend API implementations (`HasErrors` and `Message` could definitely be header values in the responses...) and since the network API shouldn't really change so often, implementing every possible response as a separate type is only a one-time cost and it's still flexible enough to be easily maintained.

Speaking of maintenance, imagine a junior dev stumbling upon the "magic" around generic network responses with custom converters in your code on the long run. I wouldn't want to be in their shoes. 😅 

Just my 2 cents here. 😄

**Comment by grahamsmith** [comment]
Interesting. I'm torn to be honest. I don't like the repetition in those examples and documentation is a good part of delivery so no one should be confused.

I don't like having to define the converter that way. Code gen could sort it out but I'd like something better.

There is a decent amount of commentary on the web about wrapped responses and not many working examples. Not every Dev has control of the API they are dealing with, as much as we would love to 😄

Do you have a complete worked example of the above? I'd like to see the comparison and weigh it up.

**Comment by grahamsmith** [comment]
Just realised @stewemetal comments may not be for what I posted! 😅

Imagine if threads were a thing 😄

**Comment by dgulmez** [comment]
@stewemetal 👍 and @grahamsmith 👍, thanks for the advices . I will apply one of them.  

About the generic response, It makes us code less on server side. We don't need to create different classes for those responses with different types. Imagine an API for a large system with  1000+ different models (plus their collections) It is not so good to so many response classes when coding an API for it. Generic response solved this for us

I thought maybe Chopper had a feature to solve this on client side, just like it handles List<T>.

Because I don't see much essential differences between List<T>  and WebResponse<T> in this context.
One carries a list of T objects along with other functionalities,  other one carries a single T object with some additional information. 

Response model can be a little bit more complicated than my original example. Such should be contained in the model itself, not http headers

For example: 

class WebRespone
{
	bool HasErrors;
	WebMessage[] Messages;
	object ReturnValue;
}

class WebMessage {
	WebMessageType Type;
        string CustomMessageCode;
	string Content;
}

enum WebMessageType{
        Information,
        Error,
        Warning
    }

**Comment by stewemetal** [comment]
@dgulmez I do see your point. I know I'm beating a dead horse here, as you're probably already deep in the project, and not just starting it now. 

So this is just for future reference: with 1000s of network models, you have to code 1000s of classes anyway eventually (if you want to stay type safe on both BE and FE of course).
For new projects, where we have control over the BE, we (I mean where I work) tackle this challenge with OpenAPI descriptors, as interface contracts between the BE and the FE. Code generators do the heavy lifting from there, generating all the model classes. 🙂

However, I see your point here. We should investigate the possibility of implementing response conversion with classes having generic type parameters in Chopper.

**Comment by grahamsmith** [comment]
:+1: for openAPI

@stewemetal is there a generator compatible with Chopper?

**Comment by stewemetal** [comment]
No official one from us, but check out #99 (for a more direct reference: [swagger_dart_code_generator](https://pub.dev/packages/swagger_dart_code_generator)).

It was made for 3.0.5, but 3.0.6 didn't introduce breaking changes, and neither will 3.0.7 (as semantic versioning would suggest of course 😄), so the swagger generator should work just fine.

**Comment by JEuler** [comment]
@techouse Thank you so much for cleaning up the issues! 🤗
