### ISSUE TITLE
[REQUEST] Type for Parts in MultiPart requests

### ISSUE THREAD

**Issue by Hyla96** [lejard-h/chopper#200]
Wouldn't it be nice to be able to assign the content-type to parts in multiparts requests? Right now you can do it for files, but for Part() you can't. In my case I need it, otherwise if my backend doesn't see the "application/json" starts complaining :)

**Comment by erlangparasu** [comment]
https://github.com/lejard-h/chopper/issues/160#issuecomment-1693253774
