### ISSUE TITLE
Resolve request inside interceptor

### ISSUE THREAD

**Issue by hatem-u** [lejard-h/chopper#202]
Hello 👋 

I'm in a bit of a pickle here. I'm trying to cache my network calls and I thought I could do it through implementing `RequestInterceptor` and `ResponseInterceptor` in my cache class but I quickly realized that I cannot return a response in my `onRequest` function to resolve the request early.

I'm working around this in a very sketchy manner at the moment and I would love if you give me pointers or examples on how you would do caching using chopper.

**Comment by HatEmU** [comment]
I think the best solution would be to make a subclass of `http.BaseClient` and do my caching in the `send` function. Still looking for your input, though!

**Comment by saisasanksunkavalli** [comment]
@HatEmU  Did you find any solution for this? Even i am trying to implement my own Caching mechanism, wanted to resolve request inside the Interceptor itsef

**Comment by HatEmU** [comment]
@saisasanksunkavalli yes I made a subclass of the Client class in the http package where I implemented all my caching and I pass that to Chopper. There is no way to do it in the interceptor.
