### ISSUE TITLE
Update pub dev changelog to 3.0.6

### ISSUE THREAD

**Issue by grahamsmith** [lejard-h/chopper#208]
![Screenshot_20210304-214634](https://user-images.githubusercontent.com/1571527/110035343-71bdcb80-7d33-11eb-8f86-00c8d241f17f.png)

Appreciate it's a boring issue but have been legitimately asked by other devs what version chopper is at over confusion.

The pub Dev changelog stops at 3.0.3 but it does say 3.0.6 in the title and pub dev banner. Would be good to know if there were breaking changes etc.

**Comment by stewemetal** [comment]
Thanks for pointing this out!

We're working on this, I'd really like to facilitate proper changelogs starting with 3.0.7.

@lejard-h Can we align regarding this?

**Comment by lejard-h** [comment]
Don't know why we went from `3.0.3` to `3.0.6`

Anyway will follow [semver](https://semver.org/) so no breaking change in `3.0.6` just documentation improvment
