### ISSUE TITLE
SSL pining

### ISSUE THREAD

**Issue by Darshan0** [lejard-h/chopper#209]
Is SSL pining supported in chopper

**Comment by ozkayas** [comment]
+1
Or, any way how to implement SSL pinning with Chopper?

**Comment by JEuler** [comment]
I haven't worked with it, but as I understand, as Chopper is using HttpClient, you can use https://gist.github.com/samrat19/52d2e004cfd8155a568d05fc80bc7642#file-ssl_pinning-dart this code as example to instantiate HttpClient and provider ChopperClient with that client
