### ISSUE TITLE
A problem bewteen build_runner and chopper

### ISSUE THREAD

**Issue by vero-jasper** [lejard-h/chopper#213]
I got a problem after  **1.25.0-8.3.pre** on branch beta, when i use **chopper(3.0.6)**.
I created a chopper service's abstract class, and ran build_runner to generate the implement class, there was no service code in the generated code.However, this implement class will be correct before **1.26.0**.

**And this bug is still existing on stable(2.0.1) in flutter**

<img width="662" alt="2021-03-09 19 56 27" src="https://user-images.githubusercontent.com/53299212/110467192-ac4bad80-8111-11eb-9535-177245add979.png">

<img width="662" alt="2021-03-09 19 56 41" src="https://user-images.githubusercontent.com/53299212/110467216-b4a3e880-8111-11eb-8f54-fdb4a3ac1108.png">

**Comment by stewemetal** [comment]
Hi,

We are actively working on updating chopper for Flutter 2. See #212 .

We'll get back to this issue if it still persists after the update is published.  😉 

Thank you for your patience!

**Comment by vero-jasper** [comment]
> Hi,
> 
> We are actively working on updating chopper to be compatible with Flutter 2. See #212 .
> 
> We'll get back to this issue if it still persists after the update is published. 😉
> 
> Thank you for your patience!

Thanks for your replyment!

**Comment by JEuler** [comment]
https://pub.dev/packages/chopper/versions/4.0.0-nullsafety.1
