### ISSUE TITLE
Update the Readme on pub.dev

### ISSUE THREAD

**Issue by stewemetal** [lejard-h/chopper#226]
Hey guys,

We have this on pub.dev:

![image](https://user-images.githubusercontent.com/5860632/112731372-14362c80-8f37-11eb-877e-852ed33ce7fa.png)

I believe we should update it to match 4.0.0-nullsafety.0 (or use the existing [chopper/README.md](https://github.com/lejard-h/chopper/blob/develop/chopper/README.md). Also, we should add the Flutter Favorite badge to be visible on pub.dev.

Wdyt?

@lejard-h Is this something that's easy to do?

**Comment by stewemetal** [comment]
Oh, I see that if one clicks on the prerelease link, it looks good. Let's try to push 4.0.0 stable out asap! 😅

**Comment by JEuler** [comment]
So, what we need to do, to call 4.0.0 stable? :)

**Comment by MoralCode** [comment]
it appears this is no longer an issue?

**Comment by stewemetal** [comment]
Closing this as it's no longer an issue. 🙂
