### ISSUE TITLE
chopper_generator fully null safe

### ISSUE THREAD

**Issue by lejard-h** [lejard-h/chopper#230]
Currently blocked by code_builder

https://github.com/dart-lang/code_builder/issues/303

**Comment by anilraok** [comment]
code_builde has null safety now

**Comment by anilraok** [comment]
> Currently blocked by code_builder
> 
> [dart-lang/code_builder#303](https://github.com/dart-lang/code_builder/issues/303)

code_builde has null safety now

**Comment by JEuler** [comment]
https://github.com/lejard-h/chopper/pull/248

**Comment by JEuler** [comment]
Upgraded in mentioned PR (https://github.com/lejard-h/chopper/pull/248)
