### ISSUE TITLE
 Using moor generated model json factory in chopper converter

### ISSUE THREAD

**Issue by Simouche** [lejard-h/chopper#235]
Any solution about this special case?
[details](https://stackoverflow.com/questions/66846553/flutter-using-moor-generated-model-json-factory-in-chopper-converter)

**Comment by stewemetal** [comment]
Hi,

First of all, using (generated) database model classes also as network model classes can introduce a few problems (like architectural rigidity) on the long run. [See this comment for hints.](https://github.com/lejard-h/chopper/issues/114#issuecomment-597900610)

However, if you must go with the approach you described in the SO question, have a look at the [documentation of Converters](https://github.com/lejard-h/chopper/blob/develop/converters/converters.md).
