### ISSUE TITLE
Exposed authenticator in chopper.dart

### ISSUE THREAD

**Issue by grahamsmith** [lejard-h/chopper#246]
Easy one - the authenticator has to be imported by

```import 'package:chopper/src/authenticator.dart';```

vs 

```import 'package:chopper/chopper.dart';```

Suspect the simple fix is to add 

```export 'src/authenticator.dart';``` to chopper.dart

**Comment by JEuler** [comment]
Yeah :)

**Comment by JEuler** [comment]
We have merged it :)
