### ISSUE TITLE
Digest Authentication

### ISSUE THREAD

**Issue by Andresteve07** [lejard-h/chopper#25]
Hello. Is digest authentication supported? In that case, could you provide a usage example? Thank you.

**Comment by lejard-h** [comment]
I am not familiar with digest authentication. Similar to Bearer Token ?

You can intercept each request/response using Interceptor on your chopper client

```
final chopper = new ChopperClient(
   interceptors: [
     (request) async => request.replace(body: {}, headers: {}),
   ]
);
```

**Comment by lejard-h** [comment]
You can also try to use this package as an http client https://github.com/marcoesposito1988/http_auth

**Comment by kappakan** [comment]
with above package
chopper = ChopperClient(
        baseUrl: SERVER_ADDRESS,
        client: DigestAuthClient(username, password),
        services: [
          ApiService.create()
        ],
      );
this worked for me
