### ISSUE TITLE
Upgrade build runner to ^2.0.0

### ISSUE THREAD

**Issue by fryette** [lejard-h/chopper#250]
Need to upgrade build runner to the latest version, probably as part of @JEuler request with built_value

**Comment by JEuler** [comment]
Yeah, but we need some changes on the built_value side
https://github.com/google/built_value.dart/pull/1028

**Comment by fryette** [comment]
Great! ANyway Google should update it)

**Comment by Alqueraf** [comment]
That PR on `built_value` was finally merged!
It is now available on version `8.0.6`.
