### ISSUE TITLE
Update code_builder to  ^4.0.0

### ISSUE THREAD

**Issue by IliaKhuzhakhmetov** [lejard-h/chopper#251]
When i use both libraries: floor and chopper i have some errors like this
Because chopper_generator >=4.0.0-nullsafety.0 depends on code_builder ^3.7.0 and floor_generator >=1.1.0 depends on code_builder ^4.0.0, chopper_generator >=4.0.0-nullsafety.0 is incompatible with floor_generator >=1.1.0.

**Comment by boylenssen** [comment]
```
../../.pub-cache/hosted/pub.dartlang.org/chopper_generator-4.0.0-nullsafety.1/lib/src/generator.dart:563:29: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
      pb.defaultTo = Code(p.defaultValueCode);
                            ^

```

I'm running into this now by overriding the version of `code_builder` to `4.0.0`

**Comment by JEuler** [comment]
https://github.com/lejard-h/chopper/pull/248 upgraded here
