### ISSUE TITLE
Chopper generator build runner null

### ISSUE THREAD

**Issue by BismeetSingh** [lejard-h/chopper#254]
I get an error message while trying to use chopper generator with build runner: boolean expression must not be null
Here is the code for the api:
`
import 'package:bloc_example_retrofit/models/categories.dart';
import 'package:chopper/chopper.dart';

import '../model_converter.dart';

part 'api_service.chopper.dart';

@ChopperApi()
abstract class ApiService extends ChopperService {
  @Get(path: '/categories.php')
  Future<Response<Categories>> getCategories();

  static ApiService create() {
    final client = ChopperClient(
      baseUrl: 'https://api.themoviedb.org/3',
      interceptors: [HttpLoggingInterceptor()],
      converter: ModelConverter(),
      errorConverter: JsonConverter(),
      services: [
        _$ApiService(),
      ],
    );
    return _$ApiService(client);
  }
}

`

**Comment by JEuler** [comment]
Seems duplicate (https://github.com/lejard-h/chopper/issues/262)? Will try to publish PR today to fix it.

**Comment by JEuler** [comment]
Could you please try 4.0.1?
