### ISSUE TITLE
Fail to get chopper_generator  due to clashes with lottie  lib depended on logging 1.0.0

### ISSUE THREAD

**Issue by parmarravi** [lejard-h/chopper#255]
Hi,
I am not able to build the project. As I am using Lottie in my project that is using the latest logging. chopper_generator  is throwing an error due to older logging.
Please update it.

Lib

dependencies
  chopper: ^3.0.6

dev_dependencies:
  chopper_generator: ^3.0.6
  build_runner: ^1.12.1

> ecause chopper >=3.0.3 <4.0.0-nullsafety.0 depends on logging ^0.11.4 and lottie 1.0.1 depends on logging ^1.0.0, chopper >=3.0.3 <4.0.0-nullsafety.0 is incompatible with lottie 1.0.1.
> And because no versions of lottie match >1.0.1 <2.0.0, chopper >=3.0.3 <4.0.0-nullsafety.0 is incompatible with lottie ^1.0.1.
> So, because ExampleProject depends on both lottie ^1.0.1 and chopper ^3.0.6, version solving failed.
> pub get failed (1; So, because ExampleProject depends on both lottie ^1.0.1 and chopper ^3.0.6, version solving failed.)

**Comment by JEuler** [comment]
Hi! It should be okay now, for 4.0 version. :)
