### ISSUE TITLE
Upload image failure

### ISSUE THREAD

**Issue by kimbummen** [lejard-h/chopper#26]
I want upload a image to avatar of user: 

`List<int> bytes = image?.readAsBytesSync();

@Post(path: "/user/patient/uploadAvatar")
  @multipart
  Future<Response> updateAvatar(@FileField('avatar') List<int> bytes);`

![image](https://user-images.githubusercontent.com/13693453/52926784-db93f400-3369-11e9-893f-abf86d4177bc.png)
And : 
- Upload by chopper fail 
- Upload by postman success 
- Future<Response> updateAvatar(@FileField('avatar') String path); -> success
Can you help me check my wrong code ?

**Comment by lejard-h** [comment]
What kind of error do you get ? a RuntimeException or an error from your server, or it just don't work ?
Can you post the working Curl request ?

**Comment by MahdiPishguy** [comment]
@thanhvn-15 how to you resolve your problem?
