### ISSUE TITLE
type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by mizzb** [lejard-h/chopper#262]
build runner throws this error.

[SEVERE] chopper_generator:chopper_generator:

type 'Null' is not a subtype of type 'String' in type cast
package:chopper_generator/chopper_generator.dart 7:69                   chopperGeneratorFactory
package:build_runner_core/src/package_graph/apply_builders.dart 179:47  new BuilderApplication.forBuilder.<fn>.<fn>.<fn>
dart:async                                                              runZonedGuarded

**Comment by JEuler** [comment]
What SDK you are using from pubspec?

**Comment by mizzb** [comment]
sdk: ">=2.12.0 <3.0.0"

**Comment by fryette** [comment]
same for me

**Comment by Vovanella95** [comment]
same issue on my side

**Comment by Vovanella95** [comment]
Here is my pubspec.yaml

`name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.0
  
dev_dependencies:
  swagger_dart_code_generator:
    path: ../
  chopper_generator: ^4.0.0
  build_runner: ^2.0.4
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3`


If I comment chopper_generator - everything generates. Else - error about null safe
Possiblt it will be helpful

**Comment by Vovanella95** [comment]
according this
Builder chopperGeneratorFactory(BuilderOptions options) =&gt;    chopperGeneratorFactoryBuilder(header: options.config['header']);

looks like now it's mandatory to set 'header' option for chopper_generator in build.yaml.



with
 builders:
      chopper_generator:
        options:
          header: 'azaza'

everything works well

**Comment by Vovanella95** [comment]
chopper_generator: ^4.0.0 - Failing

chopper_generator:
  path: ../chopper_generator - Works well. Looks like on pub.dev it launches in different way or chopper_generator in repository is different from pub.dev version

**Comment by Vovanella95** [comment]
https://github.com/lejard-h/chopper/commit/f25fbe4a9e2eab08424f48030d271681a37ca2ba

Looks like it fixes an issue.
You need just publish a new version

**Comment by JEuler** [comment]
Okay, I will publish it tomorrow. I have contacted @lejard-h and received instructions, will try them tomorrow. I'm on vacation and it is late for me :)

**Comment by Vovanella95** [comment]
Thaks! Sorry for interruption.  Enjoy your vacation!

**Comment by JEuler** [comment]
4.0.1 released, should we working now!

**Comment by JEuler** [comment]
Because it was working for me without this patch, please check the fix and write here, if possible :)

**Comment by ivoberger** [comment]
Note for anybody who has issues with `4.0.1`: run a `flutter clean`. Fixed it for me.

**Comment by JEuler** [comment]
Thanks all!
