### ISSUE TITLE
Code generation is not working after upgrade

### ISSUE THREAD

**Issue by strmchsr** [lejard-h/chopper#270]
I am getting following errors in all my service files:

**"line 47, column 50 of .: Expected to find ')'.
   ╷
47 │ @override Future<Response<dynamic>> getCities(Map<String*, dynamic>* body) { final $url = 'BASE_URL/city_list';."**

chopper version is : 4.0.1
flutter version is : 2.2.0

**Comment by sanni-aubergine** [comment]
@lejard-h Please look at injectable_generator
They let developer specify if they want to generate null safe version of code or not.
This way, people like me, who want to upgrade their packages to null safety but not the handwritten code can slowly move forward to prepare their project for further migration

**Comment by sanni-aubergine** [comment]
https://github.com/Milad-Akarie/injectable/blob/82a84b8cd557055c9cf3cd4d9495f25a34beef14/injectable_generator/lib/generators/injectable_config_generator.dart

`useNullSafetySyntax`

Please look at the above file to understand how do they let users decide weather developer wants to generate code with null safety or not

**Comment by prasadsunny1** [comment]
Need help

**Comment by prasadsunny1** [comment]
Waiting for a comment from the maintainer

**Comment by fryette** [comment]
@sanni-aubergine 
Null safe is the future of dart and flutter, why you need not null safe code?
It's quite a lot of effort to support both versions.

@strmchsr would be nice if you can share full sample. or at least file....

**Comment by strmchsr** [comment]
@sanni-aubergine had to downgrade the flutter version (didn't have bandwidth to do the migration)
working combination:
flutter : 1.22.6
 chopper: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  mobx_codegen: ^1.1.0+1
  built_value_generator: ^7.1.0
  chopper_generator: ^3.0.4

**Comment by JEuler** [comment]
Hm, but it will work with the recent dart...

**Comment by prasadsunny1** [comment]
Thanks, I'll try to use this workaround

**Comment by fryette** [comment]
I'm using chopper with 2.2.2 and 2.2.3 for more than 100 different requests and everything is absolutely fine.
I'm pretty sure that problem in your project because it's not ready for null safe.
Please upgrade project to null safe version and try

**Comment by JEuler** [comment]
I'm closing this theme, feel free to reopen.

**Comment by adammach** [comment]
I had the same problem because I forgot to upgrade environment in pubspec.yaml. With value:
`environment:
  sdk: ">=2.12.0 <3.0.0"`
working fine
