### ISSUE TITLE
Support dynamic parameters in base URL

### ISSUE THREAD

**Issue by jezsung** [lejard-h/chopper#271]
I'd like to do something like the below but it seems not working. Prefixing dynamic parameters for every certain request would be a great feature.

``` dart
@ChopperApi(baseUrl: "/users/{id}/followers")
abstract class FollowerService extends ChopperService {
  static FollowerService create([ChopperClient? client]) => _$FollowerService(client);

  @Get(path: '/')
  Future<Response> getFollowers(@Path('id') String id);

  @Get(path: '/count')
  Future<Response> getFollowerCount(@Path('id') String id);
}
```

**Comment by techouse** [comment]
@jezsung is this still an issue? If I understand your question correctly it's about [path parameters](https://hadrien-lejard.gitbook.io/chopper/requests#path-parameters) and those have been working for quite some time now.

**Comment by techouse** [comment]
Fixed in https://github.com/lejard-h/chopper/pull/493
