### ISSUE TITLE
Encoding space in request parameter (+ or %20)

### ISSUE THREAD

**Issue by tremp-m** [lejard-h/chopper#277]
Hello.
In utils.dart (chopper-4.0.1) for encoding request parameters is using:
String _normalizeValue(value) => Uri.encodeQueryComponent(value.toString())

and encodeQueryComponent encode space to "+". I found some services that can't correct decode that.
Why we can't manage this encoding (as far as I understand - at the present time it is %20 more common)?

**Comment by JEuler** [comment]
But it seems logical to use the standard (`dart:core`) method to encode request params? 
https://api.dart.dev/stable/2.13.4/dart-core/Uri/encodeQueryComponent.html

**Comment by JEuler** [comment]
Oh, I see, https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20

**Comment by tremp-m** [comment]
I agree that it is logical. At first sight. But did it turn out right in the end? ) I don't know which is more correct - + or %20. I see there are doubts. But, as I wrote, there are services above that do not correctly recognize +. Especially since there is an encodeComponent function in uri.dart - it looks like it can solve the problem...

**Comment by tremp-m** [comment]
> Maybe we should go with `encodeComponent`

i think yes. Can you give manage this option?

**Comment by JEuler** [comment]
Yeah, let me create the PR. :)

**Comment by JEuler** [comment]
https://github.com/lejard-h/chopper/pull/278

**Comment by tremp-m** [comment]
Thx. I will be satisfied with that correction. You decided not to make an option, but hardcode another function )
Will someone have problems with that?

**Comment by JEuler** [comment]
As I understand, 
"%20 is a valid way to encode a space in either of these contexts." from the https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20

So, the %20 is more general-purpose. :)
