### ISSUE TITLE
example depends get result in 'version solving failed'

### ISSUE THREAD

**Issue by rockyoung** [lejard-h/chopper#281]
No matter how I modify to the dependencies of **pubspec.yaml**, the example can't get the dependencies correctly via `flutter pub get` because of *incompatible* versions. I tried update all depends in it but still not working :(

**Comment by MoralCode** [comment]
i get the same thing using
```
build_runner: ^1.12.2
chopper_generator: ^4.0.1
```
seems like build_runner needs a version bump and bumping it to `build_runner: ^2.1.1` (its current latest version) seems to resolve the issue.

I have yet to fully test if this major version bump creates any issues
