### ISSUE TITLE
Possible to automate generation of *.chopper.dart files when running a normal flutter build?

### ISSUE THREAD

**Issue by MoralCode** [lejard-h/chopper#285]
it took me a while to figure out how to generate the `*.chopper.dart` files using the `pub run build_runner build` command from the FAQ document. Is there a way that this step of generating files can be set up so that it runs automatically as part of the usual `flutter build`process?

I'd like to avoid committing generated files to my repo and I would prefer to avoid creating a separate `.sh` script just to run these two commands as part of a singlular build process.

**Comment by fryette** [comment]
Unfortunately, it's a default way how generation works.
Before the run, you should run that command which provides .g, .chopper and other files.

But at the same time, I'm pretty sure you can configure VS code or Android Studio to do during the build process.

Thanks for understanding. We will update our README to make the process more clear.
