### ISSUE TITLE
Cannot unit test Chopper classes as they don't support equality

### ISSUE THREAD

**Issue by guymclean** [lejard-h/chopper#290]
We have an interceptor that appends headers to the request based on dynamic values, and we would like to unit test this interceptor. Currently we are unable to do so because the Request class (and Response) do not override == and hashCode. This means that even though the two objects, expected and actual have the same fields, the tests fail because they are different instances. Would it be possible to include this in a future release (the equatable package might help) so that users of the library are able to test their code? Thanks

**Comment by techouse** [comment]
Great idea! I'll look into implementing [equatable](https://github.com/felangel/equatable)

**Comment by techouse** [comment]
@guymclean can you check if https://github.com/lejard-h/chopper/pull/410 implements everything you wanted?
