### ISSUE TITLE
Code is not generated if @Path has dollars '$'

### ISSUE THREAD

**Issue by Vovanella95** [lejard-h/chopper#295]
Hi, I have an issue with generation fields with dollars

`@Query('someTitle\$') String? name, //not generated`

`@Query(r'someTitle$') String? name, //not generated`

`@Query('someTitle') String? name, //works fine`

**Comment by JEuler** [comment]
I have released the new version. Could you please check if it helped? :)

**Comment by Vovanella95** [comment]
Hi, thanks a lot! I will check it asap and let You know!

**Comment by Vovanella95** [comment]
Hi @JEuler ,
Thanks works fine now!

**Comment by JEuler** [comment]
Hoooray
