### ISSUE TITLE
FormatException (FormatException: Unexpected end of input (at character 1)

### ISSUE THREAD

**Issue by lucasdidur** [lejard-h/chopper#298]
When the server return 204 with empty body, JsonConverter throws a error.

Could you add some way that we can return body null when the server returns 204 status code?

Here my JsonConverter, I use JsonSerializable.

```dart
import 'package:appserap/dtos/autenticacao.dto.dart';
import 'package:chopper/chopper.dart' hide Post;
import 'package:logging/logging.dart';

typedef JsonFactory<T> = T Function(Map<String, dynamic> json);

class JsonSerializableConverter extends JsonConverter {
  final log = Logger('JsonSerializableConverter');
  final Map<String, JsonFactory> factories;

  JsonSerializableConverter(this.factories);

  T? _decodeMap<T>(Map<String, dynamic> values) {
    final jsonFactory = factories[T.toString()];
    log.fine("jsonFactory: $jsonFactory");

    if (jsonFactory == null) {
      log.warning("jsonFactory is null");
      return null;
    }

    return jsonFactory(values);
  }

  List<T> _decodeList<T>(List values) {
    return values.where((v) => v != null).map<T>((v) => _decode<T>(v)).toList();
  }

  dynamic _decode<T>(entity) {
    if (entity is Iterable) {
      return _decodeList<T>(entity as List);
    }

    if (entity is Map) {
      return _decodeMap<T>(entity as Map<String, dynamic>);
    }
    return entity;
  }

  @override
  Response<ResultType> convertResponse<ResultType, Item>(Response response) {
    final jsonRes = super.convertResponse(response);
    // some like if jsonRes.body == "" {return jsonRes.copyWith<ResultType>(body: null)}
    return jsonRes.copyWith<ResultType>(body: _decode<Item>(jsonRes.body));
  }
}

final jsonConverter = JsonSerializableConverter({
  "AutenticacaoDTO": AutenticacaoDTO.fromJson,
});

```

**Comment by lucasdidur** [comment]
We need that Response body allows to be null

**Comment by fryette** [comment]
Could you please share your request annotation?
`_decode` method seems fine.

**Comment by lucasdidur** [comment]
response.statusCode = 204
response. body = ""  (String)

**Comment by JEuler** [comment]
I have released the new version. Could you please check if it helped? :)

**Comment by tony123S** [comment]
I hit this issue while file is uploading  in version `3.0.0-beta.3`

**Repo**

```Future createWithImages() async {

    var savedDir = await getApplicationDocumentsDirectory();
    String appDocPath = savedDir.path;

    final files = imageList.map((imageUrl) {
      final file = FileItem(
          path: appDocPath + "/" + FileUtils.basename(imageUrl),
          // savedDir: appDocPath,
          field: 'file[$count]');

      count++;

      return file;
    }).toList();

    try {
      final result = await InternetAddress.lookup('xxx.com');
      if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
        final taskId = await uploader.enqueue(MultipartFormDataUpload(
            url: Consts.BASE_URL +
                'xxx',
            files: files,
            data: {
                 ...
            },
            method: UploadMethod.POST,
           ));

        return true;
      }
    } catch (e) {
          .....
    }
  }```
  
  PageA.dart
  
 ```  subscription = uploader.result.listen(
      (result) async {
        if (result.response != null) {
          var caseResponse =
             CaseResponse.fromJson(await json.decode(result.response!));

          if caseResponse .status == 101) {
                  ...
          } else {
                 ....
        }
      },
      onError: (ex, stacktrace) {
        debugPrint(ex.toString());
      },
    );
  }```
  
  **Error**
```  
E/flutter ( 3430): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter ( 3430): java.net.ConnectException: Failed to connect to xxx.com/2606...
E/flutter ( 3430): ^
E/flutter ( 3430):
E/flutter ( 3430): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
E/flutter ( 3430): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
E/flutter ( 3430): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
E/flutter ( 3430): #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
E/flutter ( 3430): #4      JsonDecoder.convert (dart:convert/json.dart:506:36)
E/flutter ( 3430): #5      JsonCodec.decode (dart:convert/json.dart:157:41)
E/flutter ( 3430): #6      jsonDecode (dart:convert/json.dart:96:10)
E/flutter ( 3430): #7      _MainPageState.initState.<anonymous closure>
package:xxx/ui/main.dart:135
E/flutter ( 3430): #8      _MainPageState.initState.<anonymous closure>
package:xxx/ui/main.dart:133```

**Comment by santro93** [comment]
With today's package version "copywith" function not able to find from below method :-

@override
  Response<ResultType> convertResponse<ResultType, Item>(Response response) {
    final jsonRes = super.convertResponse(response);
    // some like if jsonRes.body == "" {return jsonRes.copyWith<ResultType>(body: null)}
    return jsonRes.copyWith<ResultType>(body: _decode<Item>(jsonRes.body));
  }
}

can i get any soultion for this issue?
