### ISSUE TITLE
Update build to 1.0.0 release

### ISSUE THREAD

**Issue by charafau** [lejard-h/chopper#3]
Since new build version is out with breaking changes, chopper should also use it.

**Comment by Wasylews** [comment]
Yeah, things like
> Because chopper_generator >=0.1.0 depends on build ^0.12.0 and build_runner >=1.0.0 depends on build >=1.0.0 <1.1.0, chopper_generator >=0.1.0 is incompatible with build_runner >=1.0.0.

are annoying.

**Comment by lejard-h** [comment]
sorry I forgot to publish to publish the package.

It should be good now
