### ISSUE TITLE
ChopperService response error

### ISSUE THREAD

**Issue by luis901101** [lejard-h/chopper#30]
I have the following method in a ChopperService:

```
@Post(path: "authenticate")
  Future<Response<Token>> authenticate(@Body() Authenticate authenticate);
```

Token class is as follow:

```
part 'user.g.dart';
@JsonSerializable()
class Token extends Jsonable<Token>{
  @JsonKey(name: "id_token") String token;

  Token();
  
  @override
  Map<String, dynamic> toJson() => _$TokenToJson(this);
  factory Token.fromJson(Map<String, dynamic> json) => _$TokenFromJson(json);
  factory Token.fromJsonString(String json) => _$TokenFromJson(jsonDecode(json));
}
```

When I call mySerive.authenticate(data) the following exception raises:

```
Unhandled exception:
type 'Future<Response<dynamic>>' is not a subtype of type 'FutureOr<Response<Token>>'
ChopperClient.send (package:.........)
_AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
............
```

I'm currently using JsonConverter() as the converter for ChopperClient...
Nevertheless if I remove the ```<Token>``` as:

```
@Post(path: "authenticate")
  Future<Response> authenticate(@Body() Authenticate authenticate);
```

Then the service runs fine and returns a Map with the {id_token: eyJhbGciOiJIUzUxMiJ9.ey.......}
So what can I do to get the Token as the body of my Response???

**Comment by lejard-h** [comment]
Sorry did not understand the following part `Nevertheless if I remove the as`.

What version of chopper are you using ?

**Comment by MichaelDark** [comment]
@luis901101 I think #34 should probably fix this

**Comment by luis901101** [comment]
> Sorry did not understand the following part `Nevertheless if I remove the as`.
> 
> What version of chopper are you using ?

I forget to put ```<Token>``` inside code format, and the text doesn't show up... I already updated the *Nevertheless* part...
I am currently using chopper: ^2.1.0

**Comment by luis901101** [comment]
@MichaelDark you're right  [#34](https://github.com/lejard-h/chopper/pull/34) is the same that I asked but with lists. Thanks I will check with version 2.2.0

**Comment by MichaelDark** [comment]
@lejard-h I think it is time to close this issue
