### ISSUE TITLE
QueryMap buildUrl 

### ISSUE THREAD

**Issue by vanyastaff** [lejard-h/chopper#301]
When use QueryMap to get url like example/?filter[age][to]=23&filter[age][from]=14 but I get example/?filter.age.to=23&filter.age.from=14 . :( It make some problem when use some official API. How to solve this problem?

I find code 
if (prefix != null) {
  name = '$prefix.$name';
}

I would more like when use '$prefix[$name]';

**Comment by techouse** [comment]
I'm working on adding a feature that will support that.

**Comment by techouse** [comment]
Fixed in v5.0.1. Closing this issue.
