### ISSUE TITLE
Handle Response With status=204

### ISSUE THREAD

**Issue by Simouche** [lejard-h/chopper#303]
I have a DELETE api that returns a status of 204 without any content.
i tried:
```
 @Delete(path: "{id}/")
  Future<Response> ...
```
it throws a converter error, because appearantly chopper sets this to dynamic.

i also tried:
```
 @Delete(path: "{id}/")
  Future<Response<NoContentResponse>>...
```
NoContentResponse, is an empty class with no fields, and have the fromJson and toJson factories/methods.
but this also throws an error.
any idea how can i handle such use case?

**Comment by JEuler** [comment]
Not yet released, but maybe https://github.com/lejard-h/chopper/pull/292 will help. 
I have created PR with a fresh release, will notify you here when the release will proceed.

**Comment by JEuler** [comment]
I have released the new version. Could you please check if it helped? :)

**Comment by Simouche** [comment]
Still having `Error: Unhandled error Unexpected null value.`
maybe i got something wrong? can you provide an example?
I upgraded to `chopper: ^4.0.3`

**Comment by Simouche** [comment]
I worked around this issue by:

1.  changing my response body type to void: `Future<Response<void>>`.
2. override the response converter method to return null of the Json String is empty:
```
T? fromJsonData<T, InnerType>(String jsonData, Function jsonParser) {
    if (jsonData.isEmpty) {
      return null;
    }
    var jsonMap = json.decode(jsonData);

    if (jsonMap is List) {
      return jsonMap
          .map((item) => jsonParser(item as Map<String, dynamic>) as InnerType)
          .toList() as T;
    }

    return jsonParser(jsonMap);
  }
```
