### ISSUE TITLE
[Feature]: Can we replace the String based path with Uri() instead?

### ISSUE THREAD

**Issue by masseelch** [lejard-h/chopper#304]
Currently: 
```dart
 final r = await client.post(
          '/auth/token?cred=something%20with%20spaces',
          body: {
            'email': _email,
            'password': _password,
          },
        );
```
I propose:
```dart
 final r = await client.post(
          Uri(path: '/auth/token', queryParameters: {'cred': 'something with spaces'}),,
          body: {
            'email': _email,
            'password': _password,
          },
        );
```

Underlying http client does use Uri too. I can provide a PR if you agree with this proposal.

**Comment by JEuler** [comment]
Seems nice, could you please provide the PR?

**Comment by JEuler** [comment]
Cool, thank you very much!

**Comment by JEuler** [comment]
@masseelch Any luck with that? :) Hi!

**Comment by masseelch** [comment]
Ah, ooopsi. I completly forgot. Was on vacation and havent touched the project since then. I will try my luck tomorrow :-)

**Comment by JEuler** [comment]
Thank you very much! 🍺

**Comment by masseelch** [comment]
Buried deep in work. But I got some spare time tomorow :-)

**Comment by JEuler** [comment]
All is okay, I'm also totally in work. :)

**Comment by masseelch** [comment]
Had a look yesterday and the changes are quite huge. I won't find time to do the changes in the foreseeable future. And this is not a critical bug, just a nice to have. 

I'll leave this open, i might find time someday. Or somebody else is picking this up.
