### ISSUE TITLE
Wrong Request instance is passed to Authenticator.authenticate method

### ISSUE THREAD

**Issue by imatok** [lejard-h/chopper#308]
Hello,

this is really a small one that bugs me right now :).
Inside `send` method, Authenticator gets vanilla Request passed that hasn't been *converted* nor *intercepted*.
I'm adding some custom headers via `RequestInterceptor` that get stripped when Authenticator must do his magic, so I cannot re-send the updated request. 

```dart
Future<Response<BodyType>> send<BodyType, InnerType>(
    Request request, {
    ConvertRequest? requestConverter,
    ConvertResponse? responseConverter,
  }) async {
    var req = await _handleRequestConverter(request, requestConverter);
    req = await _interceptRequest(req);
    _requestController.add(req);
...
    if (authenticator != null) {
      var updatedRequest = await authenticator!.authenticate(request, res);
...
```
To fix it, line 314 should be:
```dart
     var updatedRequest = await authenticator!.authenticate(req, res);
```

Hope this will be on pub.dev soon ;)

BR

**Comment by JEuler** [comment]
https://github.com/lejard-h/chopper/pull/310

Sorry for delay, will try to publish it soon

**Comment by JEuler** [comment]
https://pub.dev/packages/chopper

**Comment by JEuler** [comment]
@imatok Should I close it? :)

**Comment by imatok** [comment]
Thanks for releasing it. :)
