### ISSUE TITLE
RequestConverter and ResponseConverter not propagated once again after Authenticator.authenticate gives updated request 

### ISSUE THREAD

**Issue by ravindran-a** [lejard-h/chopper#309]
Hello,

After getting an updated request and calling send on the updated Request like below,

line number 317
`res = await send<BodyType, InnerType>(updatedRequest);`

The Request/Response type converters are not further propagated and its causing type mismatch error when refreshing the token and calling the same request again using the Authenticator.

To fix it,
line number 317 can be updated as below

`res = await send<BodyType, InnerType>(updatedRequest, requestConverter: requestConverter, responseConverter: responseConverter,);`

Please consider to include this in the next pub dev version

Thanks

**Comment by JEuler** [comment]
https://github.com/lejard-h/chopper/pull/310

**Comment by JEuler** [comment]
https://pub.dev/packages/chopper

**Comment by ravindran-a** [comment]
Verified Fix Thanks for the update

**Comment by JEuler** [comment]
No, thank you! 🍺
