### ISSUE TITLE
Where can I handle any errors?

### ISSUE THREAD

**Issue by naiba** [lejard-h/chopper#315]
I've tried using ErrorConverter, ResponseInterceptor and none of them can handle the error of requesting a non-existent HTTP service or not passing in a baseUrl.

I would like to handle such errors in a fixed location to prompt the user without having to catch the error every time I initiate an HTTP request.

**Comment by naiba** [comment]
In the case of server unreachability, it is strange to need to write code that catches errors at every request.

**Comment by abdullahalamodi** [comment]
You can create class like this 
```
abstract class Result<T> {}

class Success<T> extends Result<T> {
  final T value;

  Success(this.value);
}

class Error<T> extends Result<T> {
  final Exception exception;

  Error(this.exception);
}
```

next passing the error type inside converter 

```
 if (rawResponse is Map) {
        // Called `detail(...)`
        return response.copyWith<BodyType>(
          body: Success(
            Apod.fromJson(
              {
                ...rawResponse,
                'id': rawResponse['date'],
              }.cast<String, dynamic>(),
            ),
          ) as BodyType,
        );
      } else if (rawResponse is List) {
        // Called `list(...)`
        return response.copyWith<BodyType>(
          body: Success(rawResponse
              .map<Apod>(
                (json) => Apod.fromJson(
                  {...json, 'id': json['date']}.cast<String, dynamic>(),
                ),
              )
              .toList()) as BodyType,
        );
      } else {
        return response.copyWith<BodyType>(
          body: Error(Exception('Unable to parse response')) as BodyType,
        );
      }
```

then you can check if type is Success or Error to handle it 
```
@override
  Future<T?> getItem(String id) async {
    final Response<Result<Apod>> response = await api.detail(
      date: id.toDateTimeAsDateString(),
    );

    if (response.body is Success) {
      return ((response.body! as Success<Apod>).value as T);
    } else {
      // ignore: avoid_print
      print(response.error);
    }
  }
```

you can fine full example here

**Comment by naiba** [comment]
@abdullahalamodi Hi, thank you for your reply. But as I understand it, it is unlikely that the errors mentioned above will be taken over in this way, as the errors are not handled by the Converter, ErrorConverter, or ResponseInterceptor.

Have you tried removing the baseUrl and testing if the error is handled?

**Comment by abdullahalamodi** [comment]
> 

actually I just saw the example put I didn't test it.

**Comment by abdullahalamodi** [comment]
**The errorConverter is called only on error responses (statusCode < 200 || statusCode >= 300).**

this line in the documentation maybe help

**Comment by naiba** [comment]
I have tested that there is nothing except `try...catch` or
`req.catchError` that can handle the error of requesting unreachable
service.
