### ISSUE TITLE
Depend on analyzer ^3.0.0

### ISSUE THREAD

**Issue by dJani97** [lejard-h/chopper#319]
Many other packages started to depend on `analyzer: ^3.0.0` lately. I'm unable to upgrade those since chopper_generator ^4.0.3 requires analyzer ^2.0.0.

Please upgrade to `analyzer ^3.0.0`.

**Comment by JEuler** [comment]
Yeah, of course. Will have a look soon.

**Comment by stewemetal** [comment]
Hey @dJani97 ,
Have a look at #320, the magic is happening there! 😉

**Comment by JEuler** [comment]
Release 4.0.5 is now with us

**Comment by dJani97** [comment]
Works like a charm, thank you!
