### ISSUE TITLE
CurlInterceptor never show at the terminal

### ISSUE THREAD

**Issue by dafinoer** [lejard-h/chopper#322]
i'm use `CurlInterceptor` for request logging, but i can't find the message log at the terminal when use debug mode.
![Screen Shot 2022-01-12 at 14 35 24](https://user-images.githubusercontent.com/17630268/149083739-b8e52f35-bee7-4b56-b4d2-509cd4d11a7d.png)

the message show but never seen at the terminal.
![IMAGE 2022-01-12 14:42:55](https://user-images.githubusercontent.com/17630268/149084716-73c9ccab-e111-4798-8231-5f6a453fb58c.jpg)

it's a bug or i missing something?

**Comment by JEuler** [comment]
Probably a bug, need time for investigation. Did you manage to receive the print result?

**Comment by Guldem** [comment]
Did you configure the the [logging](https://pub.dev/packages/logging)? When I tried using the `HttpLoggingInterceptor` I had to include the logging package and include it in order to see any messages.

```
Logger.root.level = Level.ALL; // defaults to Level.INFO
Logger.root.onRecord.listen((record) {
  print('${record.level.name}: ${record.time}: ${record.message}');
});
```

**Comment by techouse** [comment]
I had a similar issue when writing a CLI app. You have to do something like this in your `main.dart`

```dart
import 'package:chopper/chopper.dart';

void main() async {
  chopperLogger.onRecord.listen((record) {
    print('${record.level.name}: ${record.time}: ${record.message}');
  });

  // do stuff...
}
```
