### ISSUE TITLE
Support HTTP/3 (QUIC protocol)

### ISSUE THREAD

**Issue by muhammadsaddamnur** [lejard-h/chopper#329]
Hi, does this package support HTTP/3 (QUIC protocol) ?

**Comment by JEuler** [comment]
As I understand, nope, we are depending on HttpClient. 
https://github.com/dart-lang/sdk/issues/38595
I haven't tried to use cronet with Chopper.

**Comment by techouse** [comment]
@muhammadsaddamnur FYI [cupertino_http](https://pub.dev/packages/cupertino_http) supports http/3.

CC / @JEuler

**Comment by JEuler** [comment]
Hmmmm, cool!
