### ISSUE TITLE
Flutter latest dependecies on other library creating chopper not to work

### ISSUE THREAD

**Issue by prabinshrestha** [lejard-h/chopper#33]
my pubspec :
  chopper: ^2.1.0 # network api call like retrofit

  flutter_advanced_networkimage: ^0.4.13 #image fetch like glide or picasso
  http: ^0.11.0

Because chopper 2.1.0 depends on http ^0.11.0 and no versions of chopper match >2.1.0 <3.0.0, chopper ^2.1.0 requires http ^0.11.0.
So, because flutter_app depends on both http 0.12.0 and chopper ^2.1.0, version solving failed.

Because flutter_app depends on flutter_advanced_networkimage ^0.4.13 which depends on http ^0.12.0, http ^0.12.0 is required.
So, because flutter_app depends on http ^0.11.0, version solving failed.

**Comment by lejard-h** [comment]
will update the package soon

but if you really need it you can override dependency

```
dependency_overrides:
  http: ^0.12.0
```

**Comment by lejard-h** [comment]
should be fix in last release `2.2.1`
