### ISSUE TITLE
Chopper with Freezed Nested Json _TypeError Exception

### ISSUE THREAD

**Issue by ishaantantra** [lejard-h/chopper#330]
I have used freezed package to create the model class (data class + json_serializable).
The request is executed properly and server is receiving proper data but I am facing issue while handling response.
I am trying to catch a type-safe response (nested json response) from chopper library but I am getting the following exception

    Exception has occurred.
    _TypeError (type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'LoginResponse?')

on line 

    final loginResponse = await ApiService.authenticationService
      .login(loginRequest.toJson());

If I capture dynamic response then the code is working properly.

login.dart

    LoginRequest loginRequest = LoginRequest(
    	userId: userName,
    	password: password,
    	deviceSerialNumber: DeviceInfo.serialNumber,
    );
    final loginResponse = await ApiService.authenticationService
      .login(loginRequest.toJson());

api_list.dart

    class ApiService {
      // * For Login, Logout, Switch User
      static final authenticationService =
          AuthenticationServices.create(MainChopperClient.client);
    }

authentication.dart
   
    part 'authentication.chopper.dart';
    
    @ChopperApi(baseUrl: '/authentication')
    abstract class AuthenticationServices extends ChopperService {
      @Post(path: '/login')
      // Future<Response> login(     //Working
      Future<Response<LoginResponse>> login(     //Not Working
        @Body() Map<String, dynamic> body,
      );
    
      @Post(path: '/logout')
      Future<Response> logout(
        @Body() Map<String, dynamic> body,
      );
    
      static AuthenticationServices create([ChopperClient? client]) =>
          _$AuthenticationServices(client);
    }

login_response.dart

    import 'package:freezed_annotation/freezed_annotation.dart';
    
    /*
    {
      "data": {
        "user_id": "kbin",
        "password": "hvub",
        "device_serial_number": "abc"
      },
      "msg": "login Succesfull"
    }
    */
    part 'login_response.freezed.dart';
    part 'login_response.g.dart';
    
    @freezed
    class LoginResponse with _$LoginResponse {
      const factory LoginResponse({
        @JsonKey(name: 'msg') required String msg,
        @JsonKey(name: 'data') required LoginResponseData data,
      }) = _LoginResponse;
    
      factory LoginResponse.fromJson(Map<String, dynamic> json) =>
          _$LoginResponseFromJson(json);
    }
    
    @freezed
    class LoginResponseData with _$LoginResponseData {
      const factory LoginResponseData({
        @JsonKey(name: 'user_id') required String userId,
        @JsonKey(name: 'password') required String password,
        @JsonKey(name: 'device_serial_number') required String deviceSerialNumber,
      }) = _LoginResponseData;
    
      factory LoginResponseData.fromJson(Map<String, dynamic> json) =>
          _$LoginResponseDataFromJson(json);
    }

main_chopper_client.dart

```
class MainChopperClient {
  static final client = ChopperClient(
    baseUrl: ServerConfiguration.serverUri,
    interceptors: [
      const HeadersInterceptor({
        'Content-Type': 'application/json; charset=UTF-8',
        'Cache-Control': 'no-cache'
      }),
      HttpLoggingInterceptor(),
    ],
    services: [
      AuthenticationServices.create(),
    ],
    converter: const JsonConverter(),
    errorConverter: const  JsonConverter(),
  );
}
```

build.yaml

    targets:
      $default:
        builders:
          json_serializable:
            options:
              explicit_to_json: true

**Comment by ebrarbilgili** [comment]
why there is no answer for this issue?

**Comment by techouse** [comment]
@ebrarbilgili To me, it looks like the converter was not given any info on how to convert this type of `_InternalLinkedHashMap<String, dynamic>` to a `LoginResponse?` simply because @ishaantantra used a default `JsonConverter` and didn't specify the specific converted for `LoginResponse`.

Take a look at the example [here](https://github.com/lejard-h/chopper/blob/develop/example/bin/main_json_serializable.dart#L19).

**Comment by ebrarbilgili** [comment]
acually the thing i wonder, why there is no support for freezed package or any... It is seriously missing detail for this package, i think...

**Comment by techouse** [comment]
I'm not sure I follow. All you have to do is to wire up the `fromJson` factory of the model with its type in a `JsonConverter`. 

1. Copy [this `JsonConverter` class here](https://github.com/lejard-h/chopper/blob/develop/example/bin/main_json_serializable.dart#L65) to your codebase
2. Do something like 
```dart
final client = ChopperClient(
  // ... other stuff stuff
  converter: JsonConverter({
    LoginResponse: LoginResponse.fromJson,
  })
)
```

**Comment by JEuler** [comment]
@ebrarbilgili Does that work?

**Comment by ebrarbilgili** [comment]
yes it worked

you can find my repo:
[Chopper-Freeze Flutter](https://github.com/ebrarbilgili/chopper_demo)

**Comment by sanni-zest** [comment]
Thanks for this issue. Learned something new to implement at work. So much easier than regular api client that I used to make

**Comment by bawantha** [comment]
Why we can't directly use `JsonConverter()` which is provided by the chopper, isn't this convertor should be integrated by default in the chopper?
