### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'MyModel'

### ISSUE THREAD

**Issue by bawantha** [lejard-h/chopper#333]

**Comment by FabriBertani** [comment]
I'm having this issue too

**Comment by JEuler** [comment]
Hi! Sorry for delay (DELAY), but please provide more details. It is often related to "wrong" model implementation.

**Comment by techouse** [comment]
Duplicate of https://github.com/lejard-h/chopper/issues/330
