### ISSUE TITLE
[Feature Request] Allow to add interceptors after constructor

### ISSUE THREAD

**Issue by danielgomezrico** [lejard-h/chopper#334]
# Current
The only way to add interceptors is with the Chopper constructor

# Expected
We can add interceptors after the chopper client was initialized

# Why?
Based on your interceptor, they may require some dependencies that are not ready before the chopper client is created, for example, an interceptor that will use a service to call some endpoint when something happens in the interceptors.

**Comment by fryette** [comment]
Is it supported by chopper actually?

**Comment by techouse** [comment]
Fixed in #547
