### ISSUE TITLE
Serializer throws a `DeserializationError` instead of an `Exception`

### ISSUE THREAD

**Issue by danielgomezrico** [lejard-h/chopper#339]
When you declare a type that does not match with a response body the serializer inside of it throws a `DeserializationError` and if you catch that in your code theres a linter that rise up:

https://dart-lang.github.io/linter/lints/avoid_catching_errors.html

So this must be an error or an exception? to me it must be an exception, WDYT?

**Comment by JEuler** [comment]
Hi! What serializer?

**Comment by danielgomezrico** [comment]
@JEuler Sorry, I missed to fill the issue

**Comment by danielgomezrico** [comment]
👀

**Comment by techouse** [comment]
@danielgomezrico I assume you are referring to a `built_value` serializer?

**Comment by danielgomezrico** [comment]
Yeah! so, its more related to that and not this repo right?

**Comment by danielgomezrico** [comment]
Thanks I moved into the right repo: https://github.com/google/built_value.dart/issues/1293
