### ISSUE TITLE
ChopperClient.send not passing in Body and Item types when decoding an error response.

### ISSUE THREAD

**Issue by diegotori** [lejard-h/chopper#37]
@lejard-h, Even though the latest version passes in the Body and Item types into `_decodeResponse`, the same can't be said when the response isn't successful. This is causing it to fail when trying to decode to the ResultType in the Converter due to mismatched types after deserialization.

```
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'MyBuiltValueResponse'
```

```dart
    if (res.isSuccessful) {
      if (responseConverter != null) {
        res = await responseConverter(res);
      } else {
        res = await _decodeResponse<Body, Item>(res, converter);
      }
    } else {
      res = await _decodeResponse(res, errorConverter);
    }
```

**Comment by lejard-h** [comment]
Is is possible to share your errorConverter ?

`res = await _decodeResponse(res, errorConverter);`
here we cannot infer that `res` will be a `Response<Body>` since the response is not successful

at wich line exactly you are getting your exception ?
