### ISSUE TITLE
Query with null value included

### ISSUE THREAD

**Issue by DipDevStudio** [lejard-h/chopper#371]
In the last release 5.0.1 in query, the value is null - URL request was configurated with an empty value.

`/categories?offset=&limit=`

In the previous release, 5.0.0, these queries were not included.

`/categories`

Example:

```dart
@Get(path: 'categories')
  Future<Response<DtoPagination<DtoCategory>>> categories(
    @Header('Request-Service-Location') String service, {
    @Query('offset') int? offset,
    @Query('limit') int? limit,
  });
```

**Comment by techouse** [comment]
That is by design https://github.com/lejard-h/chopper/pull/364 most if not all backends ignore it anyway.

**Comment by DipDevStudio** [comment]
Ok, but Laravel (PHP) don't ignore it.
It perceives as a text (string), but the number (integer) is required.
So, this method is also not entirely correct and is redundant - data is transmitted that can only sometimes be useful. 

It would be correct to add a key to the annotation that is responsible for ignoring or not such data.
But if it is difficult to do this through the annotation, then you can add it to the chopper settings

**Comment by techouse** [comment]
I could add an annotation to `@Get` to truncate `null` query parameters, yes.

**Comment by techouse** [comment]
Check https://github.com/lejard-h/chopper/pull/372
