### ISSUE TITLE
@QueryMap annotation

### ISSUE THREAD

**Issue by luis901101** [lejard-h/chopper#38]
How can I define an endpoint with a dynamic query mapper which builds url requests like: http://my.server.com/api/friends?group=coworker&age=42&page=1&size=20&sort=name,asc

without having to declare a @Query for each param. Retrofit has QueryMap, I mean something like that

**Comment by lejard-h** [comment]
do you wish for something like

```dart
@Get('/friends')
Future<Response> getQuery(@QueryMap() Map<String, String> query);
```

**Comment by luis901101** [comment]
Exactly, that's a very common annotation I use when requesting list of data from an endpoint, it's very useful for example for pagination params

**Comment by luis901101** [comment]
Good. Thanks
