### ISSUE TITLE
File name not filled with provided PartFile name.

### ISSUE THREAD

**Issue by SEGVeenstra** [lejard-h/chopper#384]
## Steps to Reproduce

Create a `Multipart` endpoint:

```dart
  ///Update the profile picture of the currently logged in user
  @Put(path: '/user/profile/profile-picture')
  @Multipart()
  Future<chopper.Response> _UploadProfilePicture({@PartFile('image') List<int>? ProfilePicture});
```

**Expected results:**
To see file name filled with provided name:
![Schermafbeelding 2022-11-15 om 11 27 21](https://user-images.githubusercontent.com/5990148/201896364-9a2c8ff6-54fb-4672-b0c8-c8679ea2cd86.png)

**Actual results:** 
The file name is NOT filled:
![Schermafbeelding 2022-11-15 om 11 28 20](https://user-images.githubusercontent.com/5990148/201896588-52fbea29-671f-4acd-b50c-07a2a11a9532.png)

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by techouse** [comment]
There seems to be some confusion between `name` and `filename`.

The [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#directives) states:

> ## Directives
> - **name**
> Is followed by a string containing the name of the HTML field in the form that the content of this subpart refers to. When dealing with multiple files in the same field (for example, the [multiple](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-multiple) attribute of an [<input type="file">](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element), there can be several subparts with the same name.
> 
>   A name with a value of '_charset_' indicates that the part is not an HTML field, but the default charset to use for parts without explicit charset information.
> 
> - **filename**
> Is followed by a string containing the original name of the file transmitted. The filename is always optional and must not be used blindly by the application: path information should be stripped, and conversion to the server file system rules should be done. This parameter provides mostly indicative information. When used in combination with Content-Disposition: attachment, it is used as the default filename for an eventual "Save As" dialog presented to the user.
> 
> - **filename***
> The parameters filename and filename* differ only in that filename* uses the encoding defined in [RFC 5987](https://datatracker.ietf.org/doc/html/rfc5987). When both filename and filename* are present in a single header field value, filename* is preferred over filename when both are understood.
> 
> **Warning**: The string following filename should always be put into quotes; but, for compatibility reasons, many browsers try to parse unquoted names that contain spaces.

The `'image'` in your code above
```dart
@PartFile('image') List<int>? ProfilePicture
``` 
will be used for the `name` directive, not the `filename` directive. The `filename` should come from the filename itself, not the filed name.

I've added a test in #392 and the payload is:

```
--dart-http-boundary-toSsTmjmiwqNnuvECtOHtqjfYewWWL_bp5FHetVcsri-Uzwfckn
content-type: application/octet-stream
content-disposition: form-data; name="image"

PNG

IHDRÄ
IDATxc
-´IEND®
--dart-http-boundary-toSsTmjmiwqNnuvECtOHtqjfYewWWL_bp5FHetVcsri-Uzwfckn--
```

**Comment by evanholt1** [comment]
I would like to add to this issue, as i face a problem because of this.

I tried to upload a multipart file to my spring boot backend. however, I would always get back the response that the required part 'multipartFile' is not present. 

Digging deeper I found that springboot requires the fileName; not just the name, to be present with the request of the multipartFile. This is also mentioned by another person in 
https://stackoverflow.com/a/72528649/8494377. 
Following his solution to add a fileName to chopper's ToMultiPart() method, the request now worked fine.

However, as chopper does not allow writing the fileName argument to a http.multipartFile currently, I had to override a good chunk of chopper code to get this to work.

Can writing fileName arugments in http.multipartFile be added ?

**Comment by techouse** [comment]
I see your problem. Can you please make a feature request Github issue citing this issue here? I really don't want to reopen this one.

**Comment by evanholt1** [comment]
@techouse sure thing. Thanks.

**Comment by erlangparasu** [comment]
https://github.com/lejard-h/chopper/issues/160#issuecomment-1693253774
