### ISSUE TITLE
Version 5.2.0 is a breaking change

### ISSUE THREAD

**Issue by renefloor** [lejard-h/chopper#395]
## Steps to Reproduce

1. Use version 5.1.0
2. Update to version 5.2.0 without changing your code
3. Your project won't compile

Semantic versioning depends on developers upgrading a major version when there is a breaking change. PR #383 replaces strings with URI's. Of course a String is not a URI, so existing code will break working. On package level you should not commit pubspec.lock files, but that means the CI checks will pick any newest version that's in the current major, so our CI pipelines in the PR failed on totally unrelated files.

I'm not sure if it still make sense to fix this (by reverting it in 5.1.1 and releasing 6.0.0), but my main goal is to make you aware of your responsibilities as package maintainers on versioning. (I know, as I'm a package maintainer myself as well, so I'm trying to be constructive and positive.)

Major versions in semantic versioning are not just nice numbers, they have actually a function. Please use them as well for that.

**Comment by JEuler** [comment]
Hi! Yeah, that was on my mind... Sorry for inconvenience, I propose we should release the 6.0.0 version and continue to live. And proceed with semantic versioning.

**Comment by JEuler** [comment]
I will not be able to remove the 5.2.0 version from pub.dev (if it is possible for anyone) but definitely not possible for me. 
Probably we can point it out in README somewhere on very high position.

**Comment by JEuler** [comment]
Bumped to 6.0.0. Added ChangeLog note about breaking change. Again - sorry for that.

**Comment by techouse** [comment]
I take half the blame here as [v5.2.0 was initially my suggestion](https://github.com/lejard-h/chopper/pull/390#issuecomment-1347847777).

**Comment by renefloor** [comment]
> I will not be able to remove the 5.2.0 version from pub.dev (if it is possible for anyone) but definitely not possible for me.

You indeed can't. Nobody can. You could publish 5.2.0+1 or 5.2.1, but that is basically a breaking change again for anybody who already adopted 5.2.0. There is not really a way to fix this nicely. Thanks for making people aware it is a breaking change though.

**Comment by JEuler** [comment]
Yeah, I was thinking to leave it open for a while.

**Comment by RoarGronmo** [comment]
Will this say that all depending libraries / apps to 5.2.0 and 6.0.0 need to change from String to Uri from now?

**Comment by JEuler** [comment]
Hi, yeah!
