### ISSUE TITLE
Incompatibility with build_daemon

### ISSUE THREAD

**Issue by gincos** [lejard-h/chopper#40]
Since build_runner >=1.2.0, it requires build_daemon 0.2.0 at least.

`packages get` fails since chopper_generator is incompatible with build_daemon (tested in version 2.3.0)

Therefore, it is impossible to use chopper_generator with newer versions of build_runner.

I quote terminal output:

    Because no versions of chopper_generator match >2.3.0 <3.0.0 and chopper_generator 2.3.0 depends on built_collection ^3.1.3, chopper_generator ^2.3.0 requires built_collection ^3.1.3.
    So, because every version of build_daemon depends on built_collection ^4.1.0, chopper_generator ^2.3.0 is incompatible with build_daemon.

    Because build_runner >=1.2.6 <1.3.0 depends on build_daemon ^0.4.0 and build_runner >=1.2.0 <1.2.6 depends on build_daemon ^0.2.0, build_runner >=1.2.0 <1.3.0 requires build_daemon ^0.2.0 or ^0.4.0.
    And because build_runner >=1.3.0 depends on build_daemon ^0.5.0, build_runner >=1.2.0 requires build_daemon ^0.2.0 or ^0.4.0 or ^0.5.0.
    And because chopper_generator ^2.3.0 is incompatible with build_daemon (1), chopper_generator ^2.3.0 is incompatible with build_runner >=1.2.0.
    So, because nemobile_real_estate depends on both build_runner ^1.2.0 and chopper_generator ^2.3.0, version solving failed.

**Comment by lejard-h** [comment]
Hi, can you test the last version `2.3.1`, I updated built_collection

**Comment by gincos** [comment]
Seems to be fine now, thanks!
