### ISSUE TITLE
Flutter chopper generator converts body parameters from snake_case into camelCase 

### ISSUE THREAD

**Issue by ssandr1kka** [lejard-h/chopper#401]
Hey guys, I have tried to use flutter chopper generator to take some load from writing apis myself. 
The package works awesome for get requests, however when I try to do post requests things break.
Backend goes like: parameters are missing... While it expects multipart form, with snake_case parameters:
> profile_name
> profile_tag

So I looked into and 
Here is what gets generated:
```
  @override
  Future<Response<MyProfileSchema>> _apiCreateProfilePost({
    required String? profileName,
    required String? profileTag,
  }) {
    final Uri $url = Uri.parse('/api/create/profile/');
    final List<PartValue> $parts = <PartValue>[
      PartValue<String?>(
        'profileName',      <<<
        profileName,
      ),
      PartValue<String?>(
        'profileTag',          <<<
        profileTag,
      ),
    ];
    final Request $request = Request(
      'POST',
      $url,
      client.baseUrl,
      parts: $parts,
      multipart: true,
    );
    return client.send<MyProfileSchema, MyProfileSchema>($request);
  }
```

This is what should be generated:
```
  @override
  Future<Response<MyProfileSchema>> _apiCreateProfilePost({
    required String? profileName,
    required String? profileTag,
  }) {
    final Uri $url = Uri.parse('/api/create/profile/');
    final List<PartValue> $parts = <PartValue>[
      PartValue<String?>(
        'profile_name',       <<<
        profileName,
      ),
      PartValue<String?>(
        'profile_tag',          <<<
        profileTag,
      ),
    ];
    final Request $request = Request(
      'POST',
      $url,
      client.baseUrl,
      parts: $parts,
      multipart: true,
    );
    return client.send<MyProfileSchema, MyProfileSchema>($request);
  }
```

openapi.json has every value in snake case.
We are using chopper version 6.0.0

Any ways we could make it so that generated code does not convert snake_case into camelCase?

**Comment by techouse** [comment]
Hi,

Can you please post a minimal code sample to replicate the issue?

**Comment by philip6560** [comment]
@techouse this file to be edited is one of the generated files when `flutter pub run build_runner`, therefore an edit to this file would be overwritten on a second run of `flutter pub run build_runner` if there is an update in our `.swagger.json` file. Thanks.

**Comment by techouse** [comment]
I'm not sure I follow. You seem to have some complex code generation going on.

You should **never** edit auto-generated files.

That `@Part('profile_tag')` annotation should exist in your code.

**Comment by philip6560** [comment]
Oops!, we are making use of `swagger_dart_code_generator` with `chopper_generator` to generate all our apis from our `.swagger.json` file.

The point you made about not editing auto-generated files is why we are looking for a solution to have the files generated like this `@Part('profile_tag')`.

**Comment by philip6560** [comment]
Yes please, it's not a chopper issue per-se.

Thanks a lot I'd take a look at it.

**Comment by philip6560** [comment]
@techouse thanks a lot, this https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/532 is same issue. I'd follow up from there.
