### ISSUE TITLE
Connection refused not triggering error converter

### ISSUE THREAD

**Issue by anandsubbu007** [lejard-h/chopper#402]
where there is no internet connection.

clientExpectation in not triggering Error Converter.

**Comment by techouse** [comment]
Hi,

I'm not sure why a no internet connection error should trigger an Error Converter. 🤔 If there is no internet connection, the server can not even respond with an error message.

You should use the [connectivity_plus](https://pub.dev/packages/connectivity_plus) package to ensure that you don't even make HTTP calls when there is no internet.

**Comment by anandsubbu007** [comment]
even `connection refused` is also not triggered.

when server is not live.

**Comment by techouse** [comment]
It is not Chopper's responsibility to handle these errors. Closing this issue.
