### ISSUE TITLE
How to send a request with case sensitive headers ?

### ISSUE THREAD

**Issue by Mario359** [lejard-h/chopper#411]
I am making API calls to a server that does not have their headers case unsensitive.

By default, headers are converted to lower case (Authorization => authorization), which makes the server respond by 403

On the new version of Chopper 6.1.0, there is some modifications on headers ([https://github.com/lejard-h/chopper/pull/400](https://github.com/lejard-h/chopper/pull/400)).

So I would like to send a request with case sensitive headers but have no clue how to do that? What should I edit? (applyHeader(), JsonConverter())

Here is the simple code I use:
```dart
import 'package:chopper/chopper.dart';

part 'server.chopper.dart';

@ChopperApi()
abstract class ServerService extends ChopperService {
  static ServerService create() {
    final ChopperClient client = ChopperClient(
      baseUrl: Uri.parse('https://server.com/api/v1'),
      services: <ChopperService>[
        _$ServerService(),
      ],
      converter: const JsonConverter(),
    );
    return _$ServerService(client);
  }

  //TODO: Case sensitive header (Authorization)
  @Get(path: '/servers')
  Future<Response> getServersList(@Header('Authorization') final String apiKey);
}
```
How I call it:
```dart
final String apiKey = '';
final Response servers = await ServerService.create().getServersList(apiKey);
```

**Comment by Guldem** [comment]
`applyHeaders` is for combining headers and preventing duplicate headers. It only compares header base on lower case. The changes in #400 shouldn't change the case of headers. It  

So supplying header with upper case should still be passed to the server.
