### ISSUE TITLE
Failing to pass List<Map<String, dynamic>> as queryparams

### ISSUE THREAD

**Issue by Angeloem** [lejard-h/chopper#416]
## Steps to Reproduce

Try passing a list of String,dynamic maps to any CRUD method

**Expected results:** 
The uri should be in this form: https://link.domain?param[0].key=value&param[0].key1=value

**Actual results:** 
Is in this form: https://linnk.domain?param=%7key%3A%20value%2C%20key1%3A%20value1

<details>

Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_x64"
```
```

</details>

**Comment by Guldem** [comment]
Do you have more information on how you are creating these requests? Are you using the `useBrackets` attribute?

**Comment by techouse** [comment]
@Angeloem have you tried the suggestion above?

**Comment by Angeloem** [comment]
@techouse , I ended up stringifyijg the request to what I want and then passing it to the server and it worked
