### ISSUE TITLE
[Feature request] Custom error generic type please?

### ISSUE THREAD

**Issue by urusai88** [lejard-h/chopper#429]
With chopper we should manually convert Response.error object. Also we must catch the critical exceptions.
Can we have please a mechanism to catch critical errors and convert Response.error to generic type object?
Sorry for my bad english, i hope you understood me.

**Comment by techouse** [comment]
@urusai88 can you please provide an example?

**Comment by urusai88** [comment]
> @urusai88 can you please provide an example?

```dart
class MyCustomError {}

final chopper = ChopperClient<MyCustomError>(
    
);

final service = chopper.getService<...>();
final resp = await service.get();
if(!resp.isSuccessful) {
    // resp.error is MyCustomError? here
}
```

**Comment by Guldem** [comment]
Not sure I fully understand. But its possible to use a `errorConverter` which handles error responses (statusCode < 200 || statusCode >= 300). The errorConverter can return a custom error object. Only the client/service doesn't accept a generics for error types.  But its possible to cast the error from a response to the then desired custom object.

Something like:
```dart
class MyErrorConverter implements ErrorConverter  {

  @override
  FutureOr<Response> convertError<BodyType, InnerType>(Response response){
    // do something with error
    return MyCustomErrorClass();
  }
}

final chopper = ChopperClient(errorConverter: MyErrorConverter(), ...);

final service = chopper.getService<...>();
final resp = await service.get();
if(!resp.isSuccessful) {
  final myError =  resp.error as MyCustomErrorClass;
}
```

**Comment by urusai88** [comment]
@Guldem 
It is easy solution, but not type safe and forces casting every time

**Comment by Guldem** [comment]
The hard think with adding a generic type for errors is that generic need to be defined. So even if you don't care about custom errors you need to pass a type somewhere. Another solution might be to add a function/getter to response that does the logic (type checking/casting for you).

Something like(probably needs better naming): 
```dart
T? get errorOrNull<T>  {
  if(error != null && error is T) {
    return error as T;
  } else {
    return null;
  }
}
```

Then it would be something like:
```dart
final service = chopper.getService<...>();
final resp = await service.get();
if(!resp.isSuccessful && resp.errorOrNull<MyCustomError> != null) {
    // do something with your error.
}
```

You could also add this as an extension on response if you want to test it.

**Comment by Guldem** [comment]
@urusai88 The suggestion I made is now also added to chopper itself. Does this solve your request? :)

**Comment by urusai88** [comment]
@Guldem yes, thanks you
