### ISSUE TITLE
code gen ignored character escape 

### ISSUE THREAD

**Issue by humazed** [lejard-h/chopper#43]
I have `@Field("name\$re") String name,` in my request but in the generated code the escape is ignored 
the generated code:
`'name$re': name,`

this is a huge problem for me as I can't use the library at all.

**Comment by humazed** [comment]
I found a workaround by using `\\\`
so my request is ` @Field("name\\\$re") String name,` 

it solved my problem but I think this shouldn't be the default behavior and `\` should be enough.

**Comment by lejard-h** [comment]
`@Field(r"name\\\$re")` should also work

**Comment by humazed** [comment]
I think this isn't very obvious, I found it by trial and error so this
should be at least be added to documentary.
