### ISSUE TITLE
[Feature request] Sentry support

### ISSUE THREAD

**Issue by JosephNK** [lejard-h/chopper#433]
Looking at Sentry's [documentation](https://docs.sentry.io/platforms/flutter/), it seems that Http and dio support sentry.
Is there a way to apply a sentry to the chopper?
If not, it would be great if you could support it. :)

**Comment by techouse** [comment]
If I understand this correctly you just have to use `SentryHttpClient` instead of `http.Client`, correct?

**Comment by JosephNK** [comment]
Thanks for the reply :)
