### ISSUE TITLE
[Question] Is there a way to cancel the request?

### ISSUE THREAD

**Issue by JosephNK** [lejard-h/chopper#445]
I want to cancel connection during multipart upload.

Is there a way?

**Comment by techouse** [comment]
As Chopper is just a wrapper around `http` a quick Google search returns this [StackOverflow answer](https://stackoverflow.com/questions/54018383/how-to-cancel-ongoing-file-upload-sent-with-http-multipartrequest-in-flutter#answer-54025600).

However, there seems to still be an open issue https://github.com/dart-lang/http/issues/567

On a side note, please refrain from opening Github issues for user-related problems as it just adds noise. Please use StackOverflow or similar platforms for that.

**Comment by lumyxel** [comment]
https://pub.dev/packages/http/versions/1.5.0-beta#aborting-requests     Can we reopen this issue?
