### ISSUE TITLE
Cancel/Abort request

### ISSUE THREAD

**Issue by CesaTor** [lejard-h/chopper#459]
**Is your feature request related to a problem? Please describe.**
I can't see any way to cancel or abort a request after it's sent

**Describe the solution you'd like**
I've seen in retrofit that it exists something like 
`@CancelRequest() CancelToken cancelToken`
to allow the cancellation of a request.
I know this package uses http instead of dio but maybe there's a way to implement it too

**Describe alternatives you've considered**
I tried to cancel the Future in other ways or simply add a check to update the ui only if the response I get is the latest one using a scoped UniqueKey but it's pretty ugly and not that performant 

**Additional context**
I'd really like to have something like that since I'm very happy with the package and find it very robust and consistent

**Comment by fryette** [comment]
It's impossible to cancel the request if it has already been sent.
You can read more about the Cancellation token to understand how it works. You can implement such logic by yourself.
Dio is useful but, at the same time, overloaded by such features.

**Comment by techouse** [comment]
Looks like aborting HTTP requests finally lnded in https://github.com/dart-lang/http/pull/1773
