### ISSUE TITLE
error Instance of 'Response<dynamic>' only when passing wrong credentials

### ISSUE THREAD

**Issue by kappakan** [lejard-h/chopper#46]
Very weird issue:
```
try {
      _chopper = ChopperClient(
        baseUrl: SERVER_ADDRESS,
        client: DigestAuthClient(username, password),
        services: [
          _service = ApiService.create(_chopper)
        ],
        converter: JsonConverter(),
        errorConverter: JsonConverter(),
      );
      final response = await _service.login();
      print('after login');
      final int authErrCode = response.statusCode;
      print(authErrCode);
...
```
If i input proper credentials server responds with 200 and the code past `final response = await _service.login();` executes.
However, if I input incorrect credentials no code past `final response = await _service.login();`
executes(even tho I _do_ get a 401 response in postman), and I catch an error:
```

2019-04-29 14:28:59.624475: error in login(): Instance of 'Response<dynamic>':
I/flutter ( 5328): #0      ChopperClient.send (package:chopper/src/base.dart:182:7)
I/flutter ( 5328): <asynchronous suspension>
I/flutter ( 5328): #1      _$ApiService.login (file:///C:///hellogithub/lib/api/api_service.chopper.dart:56:19)
I/flutter ( 5328): #2      BlueApi.login (//api/blue_api.dart:37:39)
```

Why would I be catching such an error only if server responds with something but 200?

**Comment by kappakan** [comment]
I realised where the error is thrown(unsurpisingly in ChopperClient.send lmao) and I've just moved the rest of the code i want to execute incase of an error into catch()

**Comment by castrojr913** [comment]
It's a bug. I'm not agree your implementation is a correct fix. It's a workaround, not solution.
