### ISSUE TITLE
Retry original request inside Interceptor

### ISSUE THREAD

**Issue by s0nerik** [lejard-h/chopper#47]
OkHttp provides a [`Chain`](https://github.com/square/okhttp/wiki/Interceptors) to each interceptor. This makes it possible to easily implement failed request repetition, which is useful, for example, for refreshing access tokens.

Is there a way to replicate something like [this](https://gist.github.com/alex-shpak/da1e65f52dc916716930) with Chopper's current API?

**Comment by lejard-h** [comment]
It should be possible via a Hack, but I did not test it

```dart
ResponseInterceptorFunc retryRequest = (Response response) async {
  if (response.statusCode == 401) { //if unauthorized

    // build a new http client or use the one inside chopper if available
    final client = http.Client();

    // get base request
    final request = response.base.request;

     // and retry request
    final stream = await client.send(request);
    final res = await http.Response.fromStream(stream);

    // transform http response into a chopper response
    return Response(res, res.body);
  }
  return response;
};
```

**Comment by sarinupreti** [comment]
did this work ?

i am getting this error when i try to send refresh token in header .

Unhandled Exception: Connection closed before full header was received

**Comment by sarinupreti** [comment]
`    (Response res) async {
      if (res.bodyString.contains("9021")) {
        // m.acquire();
        final expireTime = await prefix2.authDao.getExpireTime();
        if (DateTime.now().toUtc().millisecondsSinceEpoch > expireTime) {
          try {
            final String oldRefreshToken =
                await prefix2.authDao.getRefreshToken();

            //send old refresh token and update refresh token
            await authBloc.updateRefreshToken("Refresh " + oldRefreshToken);

            final client = http.Client();

            // get base request
            final request = res.base.request;

            // and retry request
            final stream = await client.send(request);
            final newRes = await http.Response.fromStream(stream);

            return Response(newRes, newRes.body);
          } catch (e) {
            print("Error while refreshing token" + e);
          }
        }
        // m.release();
      }

      return res;
    },`

**Comment by sarinupreti** [comment]
```     (Response res) async {
      if (res.bodyString.contains("9021")) {
        // m.acquire();
        final expireTime = await prefix2.authDao.getExpireTime();
        if (DateTime.now().toUtc().millisecondsSinceEpoch > expireTime) {
          try {
            final String oldRefreshToken =
                await prefix2.authDao.getRefreshToken();

            //send old refresh token and update refresh token
            await authBloc.updateRefreshToken("Refresh " + oldRefreshToken);

            final client = http.Client();

            // get base request
            final request = res.base.request;

            // and retry request
            final stream = await client.send(request);
            final newRes = await http.Response.fromStream(stream);

            return Response(newRes, newRes.body);
          } catch (e) {
            print("Error while refreshing token" + e);
          }
        }
        // m.release();
      }

      return res;
    }, ```

**Comment by KimApps** [comment]
it's not working for me, but I need it very much. Can you test and give us working solution?

**Comment by sarinupreti** [comment]
not working here as well.

**Comment by AhmedNourJamalElDin** [comment]
I'm using BuiltValueConverter, and the solutions above seem not to work.
any quick solution for this?

**Comment by fayaz07** [comment]
> ```dart
> return Response(res, res.body);
> ```

This hack might work, if the assertion is altered ( which states interceptors shouldn't change the response)

The app encounters this issue, because of this line
```
 return Response(res, res.body);
```
```
E/flutter ( 5618): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:chopper/src/base.dart': Failed assertion: line 213 pos 7: 'body == res.body': Interceptors should not transform the body of the responseUse Response converter instead
```
If the above line is replaced with 
```
 // actual response for the request we got 401
 return Response(res, response.body);
```
the assertion is satisfied, but the final body isn't what expected.

**Comment by fayaz07** [comment]
> It should be possible via a Hack, but I did not test it
> 
> ```dart
> ResponseInterceptorFunc retryRequest = (Response response) async {
>   if (response.statusCode == 401) { //if unauthorized
> 
>     // build a new http client or use the one inside chopper if available
>     final client = http.Client();
> 
>     // get base request
>     final request = response.base.request;
> 
>      // and retry request
>     final stream = await client.send(request);
>     final res = await http.Response.fromStream(stream);
> 
>     // transform http response into a chopper response
>     return Response(res, res.body);
>   }
>   return response;
> };
> ```


This hack might work, if the assertion is altered ( which states interceptors shouldn't change the response)

The app encounters this issue, because of this line
```dart
 return Response(res, res.body);
```
```bash
E/flutter ( 5618): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:chopper/src/base.dart': Failed assertion: line 213 pos 7: 'body == res.body': Interceptors should not transform the body of the responseUse Response converter instead
```
If the above line is replaced with 
```dart
 // actual response for the request we got 401
 return Response(res, response.body);
```
the assertion is satisfied, but the final body isn't what expected.

**Comment by prudhvir3ddy** [comment]
@fayaz07 thank you very much

**Comment by SalilThreeplus** [comment]
you can also use this retry dart package which basically checks if your response contains errors and retries requests with millisecond timer which I guess is a more clean solution.

Below is the link 
https://pub.dev/packages/retry

**Comment by stewemetal** [comment]
[This](https://github.com/lejard-h/chopper/issues/47#issuecomment-671037724) is actually a thing we need to do in most Android apps that use refresh and access tokens (using Retrofit and its Interceptors of course). The `Chain` helps a lot, but there's some sweet "magic" under the hood which we might replicate sometime. 😅

**Comment by fayaz07** [comment]
@stewemetal  sweat_smile

**Comment by arjayleviackerman24** [comment]
> I'm using BuiltValueConverter, and the solutions above seem not to work.
> any quick solution for this?

Have you resolve this @AhmedNourJamalElDin . I'm experiencing same issue and also using BuiltValueConverter. I can get the new response but the response needs to be converted.

**Comment by arjayleviackerman24** [comment]
> I'm using BuiltValueConverter, and the solutions above seem not to work.
> any quick solution for this?

> I'm using BuiltValueConverter, and the solutions above seem not to work.
> any quick solution for this?

Have you resolve this @AhmedNourJamalElDin  . I'm experiencing same issue and also using BuiltValueConverter. I can get the new response based on @fayaz07   but the response needs to be converted.

**Comment by Artur512** [comment]
I have the same problem as @arjayleviackerman24 and still Im waiting for solution.

**Comment by stewemetal** [comment]
Closing this as #198 pretty much solves it. Feel free to reopen it.

**Comment by ShubhamAryanBansal** [comment]
Hi I have tried what @fayaz07 has done. As he said he altered the assertion, but in my case when I changed in chopper's base.dart class, it won't pick my changes. It is still showing the same error -> [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:chopper/src/base.dart': Failed assertion: line 213 pos 7: 'body == res.body': Interceptors should not transform the body of the responseUse Response converter instead

**Comment by ajyong** [comment]
For those who (like me) ended up here from a search, the [http] has a [RetryClient class](https://pub.dev/documentation/http/latest/retry/RetryClient-class.html). I believe you can pass this to the `ChopperClient` constructor's `client` argument.  Initially I was going to try using the `retry` package [mentioned above](https://github.com/lejard-h/chopper/issues/47#issuecomment-671881021) but was glad to see the `http` package has something already built-in.  

Moreover, the `retry` package seemed tough to integrate with Chopper's interceptors.  Correct me if I'm wrong, but with Chopper, you cannot make a `RequestInterceptor` return a `Response`, for example.  Thus, I'm looking at the `RetryClient` way instead.

[http]: https://pub.dev/packages/http
