### ISSUE TITLE
Seeking documentation clarification

### ISSUE THREAD

**Issue by edwardaux** [lejard-h/chopper#48]
Since v2.x `ChopperClient` now has a couple of new function signatures:

```
Future<Response<Body>> send<Body, Item>()
Future<Response<ResultType>> post<ResultType, ItemType>()
...
```
I must admit I have no idea what the differences are between `Body`, `Item`, `ResultType`, and `ItemType`. Are the `Body`/`Item` combo essentially representing the same thing as `ResultType`/`ItemType`, or are they totally different?  Most (all?) of the examples have `Body` and `Item` being set to the same type... when would they be different?

The notion of converters was introduced in v2.0 but, again, I'm struggling to understand how to use them effectively. For example, encoding (JSON/form) used to happen via the `@FormUrlEncoded()` annotation ... from bumbling around, I guess this has now been replaced with the `@FactoryConverter` annotation... is that right? What happens when I need to do both JSON conversion, followed by `built_value` conversion? Am I supposed to create a "chain" of converters?

It would be great (at some point) if we could get some documentation on how the new usage patterns should work. I'd be happy to create a PR ... but at the moment, I am not sure myself :)

**Comment by lejard-h** [comment]
Yes sorry, I did not update the documentation on that and I should rename stuff

`Body, Item` and `ResultType, ItemType` are the same.
It is also what you will get in converter.

```dart
  /// [ResultType] is the expected type of your response
  /// ex: `String` or `CustomObject`
  ///
  /// In the case of [ResultType] is a `List` or `BuildList`
  /// [ItemType] will be the type of the generic
  /// ex: `convertResponse<List<CustomObject>, CustomObject>(response)`
  FutureOr<Response<ResultType>> convertResponse<ResultType, ItemType>(Response response);
```

About converters, you have a global converter that you apply to your client
```dart
final chopper = ChopperClient(
    converter: FormUrlEncodedConverter(),
  );
```

But in case you want to apply a converter to a single endpoint, you can use a `FactoryConverter`,

```dart
@Post(path: '/')
@FactoryConverter(request: convertRequest, response: convertResponse)
Future<Response> postJson(@Body() Map map);

Request convertRequest(Request req) => JsonConverter().convertRequest(req);

Response<T> convertResponse<T>(Response res) => JsonConverter().convertResponse(res);
```

For Built Value converter, you can find example here https://github.com/lejard-h/chopper/blob/master/example/bin/main_built_value.dart#L54

I keep the issue open as a global improvement of documentation
