### ISSUE TITLE
how to increase timeout in chopper

### ISSUE THREAD

**Issue by shresthaRam** [lejard-h/chopper#49]
help or example needed : how to increase timeout in chopper ?

**Comment by lejard-h** [comment]
connection timeout are very limited for now due to http package, it will probably require additional work.

But if you are on vm or flutter you can set the connectionTimeout you want

```dart
import 'package:http/io_client.dart' as http;
import 'dart:io';

ChopperClient(
    client: http.IOClient(
      HttpClient()..connectionTimeout = const Duration(seconds: 60),
    ),
  );
```

related http package issue: https://github.com/dart-lang/http/issues/21
