### ISSUE TITLE
chopper base.dart send() authenticate sending wrong request

### ISSUE THREAD

**Issue by ssierputowski11** [lejard-h/chopper#492]
See [5.1.0](https://github.com/lejard-h/chopper/blob/0e5f98669e5fa9b12a55f5b3480ac92adc5517a2/chopper/lib/src/base.dart#L304) to see the authenticate is using the req object.

See [5.2.0](https://github.com/lejard-h/chopper/blob/81cf57655bd85ba5878624a9c7391a04cc626c3b/chopper/lib/src/base.dart#L311) and authenticate is using request object

See [latest](https://github.com/lejard-h/chopper/blob/203e64dd2574a02204365cd204fd97db69379607/chopper/lib/src/base.dart#L312) and similar result as above.

Is this by design? I saw another issue #308 that brings this up as well. I used that fix locally and it solved it as well. 

Could this be addressed if it is a bug?

**Comment by techouse** [comment]
Hey,

This used to be a bug that I fixed in #388.

**Comment by ssierputowski11** [comment]
> I'm not sure. Can you explain the issue you're actually facing?

Yes the authenticate call is not passing in the intercepted request. 

Original: `final Request? updatedRequest = await authenticator!.authenticate(
        request,
        res,
        request,
      );`

We could potentially have something wrong but that request object is passed through twice. Changing this value to `final Request? updatedRequest = await authenticator!.authenticate(
        req,
        res,
        request,
      );` fixes the issue that I am having. The issue being the request object does not have Header information but the req does contain the Header information

**Comment by techouse** [comment]
> The issue being the request object does not have Header information but the req does contain the Header information

I see. Can you try to pull from the PR #497 I have just created and test again

```yaml
dependency_overrides:
  chopper:
    git:
      url: https://github.com/techouse/chopper.git
      ref: fix/492-authenticator-req-request
      path: chopper
```

I've re-implemented the fix of #390 by checking if the `request.body` is already a JSON encoded `String` before attempting to `json.encode` it.

**Comment by ssierputowski11** [comment]
Looks to be reauthenticating properly and the Headers are being passed back to our override functions. Thanks! I'll keep an eye out on the updates and get this implemented when it gets updated

**Comment by techouse** [comment]
> when it gets updated

should be soon :)
