### ISSUE TITLE
is ChopperClient thread safe?

### ISSUE THREAD

**Issue by cybertriton** [lejard-h/chopper#50]
If a client concurrently submit a request to the server multiple time via a ChopperClient, every response the client receives is the last one. Is this a designed feature just like the comment in the _StreamControllerAddStreamState says?

class _StreamControllerAddStreamState<T> extends _AddStreamState<T> {
  // The subscription or pending data of a _StreamController.
  // Stored here because we reuse the `_varData` field  in the _StreamController
  // to store this state object.
  var varData;
..

**Comment by lejard-h** [comment]
Chopper use [http](https://pub.dev/packages/http) package and dart is single threaded, so yes chopper client is thread safe.

If you submit same request multiple times, each response will match the correct request
