### ISSUE TITLE
[Feature Request] Change auto generate header from http

### ISSUE THREAD

**Issue by MirzaHimamiHanif** [lejard-h/chopper#505]
**Is your feature request related to a problem? Please describe.**
 http forced to add header with `; charset=utf-8` when doing request and I want my header without it.

**Describe the solution you'd like**
Need to change the order of http.Request(). First add the body then add the header.
![image](https://github.com/lejard-h/chopper/assets/26913674/1dad9919-e015-4cee-9dbd-97fa42d89679)

**Describe alternatives you've considered**
No

**Additional context**
1. This is chopper-7.0.6 that add header first then the body
![image](https://github.com/lejard-h/chopper/assets/26913674/12d89d8f-9a22-47aa-9cb5-6bf87df76503)
2. New guide from http https://github.com/dart-lang/http/pull/1014/files

Before
![image](https://github.com/lejard-h/chopper/assets/26913674/46f541fd-dd27-4398-8f73-5d42028f907c)

After
![image](https://github.com/lejard-h/chopper/assets/26913674/c9331356-c6c2-41bf-ac19-658769299372)

**Comment by techouse** [comment]
Hey 👋 

I see. You want to remove the charset when the body is in bytes (`List<int>`), but in cases where the payload is text, it should contain `charset=utf-8`, correct?

**Comment by MirzaHimamiHanif** [comment]
I did not know that. But if that is the case it should be like this right? 

```
http.Request toHttpRequest() {
  final http.Request request = http.Request(method, url)
    ..followRedirects = followRedirects;

  if (body == null) {
    request.headers.addAll(headers);
  } else {
    if (body is String) {
      request
        ..body = body;
        ..headers.addAll(headers)
    } else if (body is List<int>) {
      request
        ..headers.addAll(headers);
        ..bodyBytes = body
    } else if (body is Map<String, String>) {
      request
        ..bodyFields = body;
        ..headers.addAll(headers)
    } else {
      throw ArgumentError.value('$body', 'body');
    }
  }

  return request;
}
```

Need to override header that is not `List<int>`

**Comment by MirzaHimamiHanif** [comment]
No, in my case I want to remove charset when the body is `Map<String, String>` and if text payload need `charset=utf-8` I think it should be like this

```
http.Request toHttpRequest() {
  final http.Request request = http.Request(method, url)
    ..followRedirects = followRedirects;

  if (body == null) {
    request.headers.addAll(headers);
  } else {
    if (body is String) {
      request
        ..headers.addAll(headers)
        ..body = body;
    } else if (body is List<int>) {
      request
        ..bodyBytes = body
        ..headers.addAll(headers);
    } else if (body is Map<String, String>) {
      request
        ..bodyFields = body;
        ..headers.addAll(headers)
    } else {
      throw ArgumentError.value('$body', 'body');
    }
  }

  return request;
}
```

**Comment by techouse** [comment]
@MirzaHimamiHanif check if #508 fixes your problem

**Comment by mirzahimami** [comment]
Yes, thanks

**Comment by techouse** [comment]
Cool, I'll add some unit tests to the PR and then merge it :)
