### ISSUE TITLE
toJson missing parent class attributes if child class's constructor does not include it 

### ISSUE THREAD

**Issue by cybertriton** [lejard-h/chopper#51]
@JsonSerializable()
class Resource {
  final String type;
  final String id;
  final String name;
  Resource(this.type, this.id, this.name);
  static const fromJsonFactory = _$ResourceFromJson;
  Map<String, dynamic> toJson() => _$ResourceToJson(this);
}

@JsonSerializable()
class ResourceA extends Resource {
  final String another;
  ResourceA(String id, String name, this.another):super('A', id, name); 
  static const fromJsonFactory = _$ResourceAFromJson;
  Map<String, dynamic> toJson() => _$ResourceAToJson(this);
}

The generated Map<String, dynamic> _$ResourceAToJson(ResourceA instance) does not include writeNotNull('type', instance.type) because it is not included in the constructor's parameters.

**Comment by lejard-h** [comment]
This issue seems to be related to [json_serializable](https://github.com/dart-lang/json_serializable) packages. Reopen an issue if you found out it is related to a conflict with chopper
