### ISSUE TITLE
DateTime query parameters should be encoded as ISO8601

### ISSUE THREAD

**Issue by wkolov** [lejard-h/chopper#515]
**Is your feature request related to a problem? Please describe.**
* We use a Swagger API description to generate code with swagger_dart_code_generator
* We have DateTime parameters in our requests, declared like
```
          {
            "name": "from",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          }
```
* Since release 2.11.11 this Swagger JSON results in Dart fields of type DateTime (before 2.11.11 they were Strings) which is considered a bugfix.
* swagger_dart_code_generator generates a bunch of classes using chopper.
* If we make a request using these generated proxies, chopper encodes DateTime parameters with toString() (https://github.com/lejard-h/chopper/blob/fedb899ff5d791c27af74c4a5b5c3da8dfcfdf03/chopper/lib/src/utils.dart#L132C1-L132C1).

It's not really a problem since DateTime.toString() is not locale-dependent, but I think ISO8601 should be used, because it's an interchange format, especially designed for interoperability.

**Describe the solution you'd like**
Use toIso8601String() for DateTime parameters.

**Comment by techouse** [comment]
Chopper does not do any data encoding. Please set up your models to do this correctly.

**Comment by techouse** [comment]
This is quite opinionated if you ask me. It should probably also be converted to UTC.

**Comment by techouse** [comment]
@wkolov check if #516 fixes your issue

**Comment by wkolov** [comment]
It works now, thanks
