### ISSUE TITLE
Unwanted trailing slash

### ISSUE THREAD

**Issue by Kavantix** [lejard-h/chopper#53]
With the current code of the generator it is not possible to avoid having a trailing slash if for instance a get request is called on the base url of the server.

It would be nice if a trailing slash is only used when explicitly given.

**Comment by lejard-h** [comment]
I made some modification in the last version `2.3.1` (generator `2.3.2`)
Default value for a path is now '' instead of '/'
This should solve your issue

**Comment by Kavantix** [comment]
@lejard-h sadly it did not help
I took a look at the code and I think it is going wrong because it is always adding the path to the base url, even if that path is empty.
