### ISSUE TITLE
Connection closed before full header was received.

### ISSUE THREAD

**Issue by bhoomikshetty** [lejard-h/chopper#533]
This issue occurs randomly while calling the APIs.
![WhatsApp Image 2023-10-10 at 18 40 17](https://github.com/lejard-h/chopper/assets/76581406/cd18f1d2-2d4e-44db-92e8-831693b21ae7)

Earlier I thought this was as issue with the IOClient. So tried a couple of fixes like -
1. Using Custom HttpClient
2. Increased the connection timeout.

but these didn't fix the issue.
When I tried calling the same APIs using http or Dio, it is working fine.

Flutter version - 3.3.10
Chopper version - 6.0.0

**Comment by techouse** [comment]
Hey,

Dio does not use `http` like `Chopper` does, so that might be the reason why it's working. 🤷

Maybe have a look at this SO answer https://stackoverflow.com/questions/55879550/how-to-fix-httpexception-connection-closed-before-full-header-was-received

**Comment by techouse** [comment]
> Can you please suggest something to make it work?

I'd start by looking at your API gateway setup.

**Comment by vishweshsoni** [comment]
Any update on this issue ?
