### ISSUE TITLE
StatusCode 204 is not handeled correctly

### ISSUE THREAD

**Issue by DarkHeros09** [lejard-h/chopper#537]
Hi

Whenever i check if statusCode == 200, it checks true, but the server is sending 204.

but when i check if the statusCode == 204 it fails.

**Comment by Guldem** [comment]
The chopper response wraps the `BaseResponse` class provided by `http` package which exposes the `statusCode` as seen [here](https://github.com/lejard-h/chopper/blob/develop/chopper/lib/src/response.dart#L49).  Chopper by itself doesn't change the `statusCode`. 

Do have some example code of your chopper setup?
