### ISSUE TITLE
chopper_generator 7.0.7 is broken

### ISSUE THREAD

**Issue by Dimous** [lejard-h/chopper#546]
Hello!
I updated chopper_generator from 7.0.6 to 7.0.7 and it stopped working.

<details>
  <summary>dart run build_runner build output</summary>
[SEVERE] chopper_generator on lib/data/client/service/rate_service.dart:

Could not format because the source could not be parsed:

line 11, column 70 of .: Expected to find ','.
   ╷
11 │ return  client.send<void, void>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                      ^^
   ╵
line 11, column 73 of .: Expected to find ','.
   ╷
11 │ return  client.send<void, void>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                         ^^^^^^^^^^^^^^^^^^
   ╵
[SEVERE] chopper_generator on lib/data/client/service/review_service.dart:

Could not format because the source could not be parsed:

line 11, column 70 of .: Expected to find ','.
   ╷
11 │ return  client.send<void, void>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                      ^^
   ╵
line 11, column 73 of .: Expected to find ','.
   ╷
11 │ return  client.send<void, void>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                         ^^^^^^^^^^^^^^^^^^
   ╵
line 15, column 70 of .: Expected to find ','.
   ╷
15 │ return  client.send<void, void>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                      ^^
   ╵
line 15, column 73 of .: Expected to find ','.
   ╷
15 │ return  client.send<void, void>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                         ^^^^^^^^^^^^^^^^^^
   ╵
[SEVERE] chopper_generator on lib/data/client/service/user_service.dart:

Could not format because the source could not be parsed:

line 14, column 102 of .: Expected to find ','.
   ╷
14 │ return  client.send<Map<String, dynamic>, Map<String, dynamic>>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                                                      ^^
   ╵
line 14, column 105 of .: Expected to find ','.
   ╷
14 │ return  client.send<Map<String, dynamic>, Map<String, dynamic>>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                                                         ^^^^^^^^^^^^^^^^^^
line 18, column 74 of .: Expected to find ','.
   ╷
18 │ return  client.send<String, String>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                          ^^
   ╵
line 18, column 77 of .: Expected to find ','.
   ╷
18 │ return  client.send<String, String>($request, requestConverter: Instance of 'BinaryExpression', ); }
   │                                                                             ^^^^^^^^^^^^^^^^^^
   ╵
</details>

| Dependency            | Version   |
|-----------------------|-----------|
| chopper | 7.0.10 |
| chopper_generator |  7.0.7 |
| build_runner | ^2.4.7 |
| analyzer              | ^6.3.0    |
| _fe_analyzer_shared   | ^65.0.0   |

When I rollback (¡only dependency!) chopper_generator to 7.0.6 it is working again.

**Comment by Guldem** [comment]
I can't reproduce it do you have some example code of the service its trying to create?

**Comment by Dimous** [comment]
Please, have a look -- https://github.com/Dimous/issue-546/blob/main/lib/rate_service.dart

**Comment by techouse** [comment]
Looks like it's starts working again when you quote out [this line](https://github.com/Dimous/issue-546/blob/main/lib/rate_service.dart#L19)

```dart
@FactoryConverter(request: FormUrlEncodedConverter.requestFactory)
```
