### ISSUE TITLE
How to send MultipartFile

### ISSUE THREAD

**Issue by humazed** [lejard-h/chopper#55]
The current method of sending a file or image is using `List<int> bytes` but this removes important info like fileName and contentType

is it possible to use `MultipartFile` like this:
https://stackoverflow.com/a/49645074/3998402

**Comment by lejard-h** [comment]
Indeed you can't pass the filename and contentType and you also can't pass a ByteStream.

I will implement the following class

```dart
class ChopperFile {
   ChopperFile.path();
   ChopperFile.bytes();
   ChopperFile.stream();

  final int length;
  final MediaType contentType;
  final String filename;
}
```

**Comment by humazed** [comment]
I think a better api would be:
taking `MultipartFile` and sending it.
or taking a `File` and generating the boilerplate code of creating `MultipartFile` 

this way it would be less class to worry about and smaller mental overhead. you want to upload a file just pass a file. similar to the convenience of Firebase Storage

    StorageUploadTask uploadTask = reference.putFile(file);

**Comment by lejard-h** [comment]
Indeed, I did not think that much about it
directly sending `MultipartFile` sounds is better

**Comment by lejard-h** [comment]
just publish `2.4.0` version
you can pass MultipartFile directly

```dart
@Post()
@multipart
Future<Response> postFile(@FileField() MultipartFile file);
```

**Comment by tony123S** [comment]
> just publish `2.4.0` version
> you can pass MultipartFile directly
> 
> ```dart
> @Post()
> @multipart
> Future<Response> postFile(@FileField() MultipartFile file);
> ```
FileField is deprecated and MultipartFile is undefined.

**Comment by Bonfs** [comment]
@tony123S Multipartfile is part of Http package and @FileField was substituted for @PartFile but i still not able to upload images using Chopper :/

**Comment by tony123S** [comment]
@Bonfs  I use other library to upload image instead of using Chopper.

**Comment by Bonfs** [comment]
@tony123S what library you are using?

**Comment by tony123S** [comment]
> @tony123S what library you are using?

flutter_uploader

**Comment by lejard-h** [comment]
@Bonfs can you fill an issue with your own bug so I can take care of it ?

**Comment by Bonfs** [comment]
Hello @lejard-h , sorry for the delay but after a lot of days trying to upload a file using Chopper I have found a solution using Part, PartFile and MultipartFile from Http package.
In the Chopper Api, my Post method:
`
@Post(
    headers: { "Content-Type": "application/x-www-form-urlencoded" }
  )
  @multipart
  Future<Response> uploadFileWithField(
    @Part("field") String field,
    @PartFile("file") MultipartFile File
  );
`
I think the header is optional but is required by the server in my case.

For instantiate the MultipartFile:
`
http.MultipartFile file = await http.MultipartFile.fromPath(
  'file',
  path,
  contentType: new MediaType('image', 'jpg')
);
`

**Comment by KhBrahim** [comment]
Hello @Bonfs , trying to upload a file(image) with data(name, address,...) using Chopper , follow your post method but the status code always 400

**Comment by SalilThreeplus** [comment]
I am getting this error while uploading image using chopper api, can anyone please help.
The name 'Response' is defined in the libraries 'package:chopper/src/response.dart (via package:chopper/chopper.dart)' and 'package:http/src/response.dart (via package:http/http.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

```
@Post(path: 'api/users/updateProfilePicture')
  @multipart
  Future<Response<BuiltUpdateProfileResponse>> updateProfilePicture(
      {@Part("field") String field,
      @FileField MultipartFile file,
      @Header("Authorization") String token});
```

Above is my api.

**Comment by Yke222** [comment]
I managed to get it working properly, you just need to use the following approach:

```
  @Post(
    path: '/test',
    headers: {
      'Content-Type': 'application/form-data',
    },
  )
  @Multipart()
  Future<Response<FileAddResponseModel>> uploadFileWithField(
    @Part('id') String id,
    @PartFile('file') MultipartFile file,
    @Part('description') String description,
  );
```

And when loading the file on controller, you should use it like that:
```
final file = await http.MultipartFile.fromPath(
      'file',
      localfile.path!,
    );
```

The localfile can be loaded as a PlatformFile.
