### ISSUE TITLE
Customize the part directive to support generating files into `.g.dart` instead of `.chopper.dart`

### ISSUE THREAD

**Issue by sbordeyne** [lejard-h/chopper#560]
**Is your feature request related to a problem? Please describe.**

- I want to speed up github action workflows, but not commit any generated files to my repo (reasons being that I don't want to deal with merge conflicts on generated code, and they clutter the repo)
- To do so, I want to use `cached_build_runner` as a drop in replacement for `build_runner` and set up a `cache` action on my GH action workflow
- Problem : `cached_build_runner` doesn't support other extensions than `*.g.dart`, so my chopper annotated classes are linted inappropriately, and the builds will fail (tests etc)
- Open issue : https://github.com/netglade/cached_build_runner/issues/8

**Describe the solution you'd like**

I want to be able to customize the expected part directive by chopper_generator, so that I can put in `api_service.g.dart` as my part directive and have it still work.

**Describe alternatives you've considered**

- Not caching my generated files (but GH actions cost money to run, I'd rather try to speed up the builds)
- Committing my generated files (but merge conflicts, clutter)
- Adding support for `*.chopper.dart` on `cached_build_runner`
- Not having a part directive for every code generation package. `*.g.dart` is already pretty ubiquitous, why have a `.chopper.dart` that makes it hard for tooling to interoperate ?

**Additional context**

- No additional context

**Comment by techouse** [comment]
Hey! Good point. I completely eluded me that this might be a use case. I'll add a builder config now.

**Comment by techouse** [comment]
@sbordeyne please check if #562 works for you.

**Comment by sbordeyne** [comment]
> @sbordeyne please check if #562 works for you.

This would be perfect for my use case (to have only .g.dart files to worry about! Thanks!

**Comment by techouse** [comment]
Can you please test it on your end as well?
