### ISSUE TITLE
flutter pub run build_runner build returns error when http method is added to the service class

### ISSUE THREAD

**Issue by Briandosha** [lejard-h/chopper#561]
## Steps to Reproduce

1. Execute `dart run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by techouse** [comment]
@Briandosha can you please elaborate with some examples?

**Comment by techouse** [comment]
Closed due to lack of info and inactivity. Feel free to open up a new issue with more information
