### ISSUE TITLE
when adding @FileField() MultipartFile the other @Field is not send

### ISSUE THREAD

**Issue by humazed** [lejard-h/chopper#58]
I have this endpoint.

```
  @Post(path: "details")
  @multipart
  Future<Response<User>> editProfile({
    @Field("carcolor") String carColor,
    @FileField() MultipartFile insurancepic,
  });
```

when I leave it as is  only `FileField` is sent

but if I remove `FileField`  `@Field("carcolor")` is sent with no problem.

```
  @Post(path: "details")
  @multipart
  Future<Response<User>> editProfile({
    @Field("carcolor") String carColor,
  });
```

when I log the request using an interceptor `request.body` is shows `carcolor` which mean the problem probably happens after the interceptors are invoked.

**Comment by lejard-h** [comment]
Indeed there is an issue in the generator I will fix it

**Comment by lejard-h** [comment]
hmm actually there is maybe a bad naming for the `FileField` annotation, it should be `PartFile` or `Part` directly, I will see if it is possible.

`Field` annotation is for form url encoded request, not form `multipart` request that don't have body.

What you want to do is probably.

```dart
@Post(path: "details")
@multipart
Future<Response<User>> editProfile({
    @Part("carcolor") String carColor,
    @FileField() MultipartFile insurancepic,
});
```

**Comment by lejard-h** [comment]
renamed `FileField` to `PartFile` this should avoid confusion
