### ISSUE TITLE
send array is not the same behavior as retrofit

### ISSUE THREAD

**Issue by humazed** [lejard-h/chopper#61]
when sending  `@Field("preferences[]") List<int> preferences` 

chopper sends:
`{ "preferences[]":[2000008,2000149] }`

retrofit sends:
`{ 
  "preferences[]":2000008, 
  "preferences[]":2000149
}`

in my app, I depend on this default behavior 

take a look at: https://stackoverflow.com/questions/53832007/how-to-send-liststring-with-retrofit

**Comment by lejard-h** [comment]
From what I see on Retrofit, it is not possible on FormUrl (and probable json) encoded data and I don't see a way to do it with `http` package in dart since body is based on HashMap.

But it should be possible for Multipart request

**Comment by humazed** [comment]
Yes, you are right, I was thinking in chopper `@Field` works with Multipart.

**Comment by lejard-h** [comment]
Related to following PR in http package https://github.com/dart-lang/http/pull/278#issuecomment-496700971

**Comment by stewemetal** [comment]
What should we do with this issue?

The referenced PR in `http` is pretty much neglected since Jun 18, 2019... :/

**Comment by lejard-h** [comment]
Indeed, maybe we should start investigate on how to do it on chopper side

**Comment by techouse** [comment]
Fixed in https://github.com/lejard-h/chopper/pull/439
