### ISSUE TITLE
Why choose it ofer retrofit?

### ISSUE THREAD

**Issue by adrianvintu** [lejard-h/chopper#633]
The documentation says: `Chopper is an http client generator for Dart and Flutter using source_gen and inspired by Retrofit.`

Can you make a table or some examples describing why we should choose copper over retrofit?

**Comment by adrianvintu** [comment]
https://pub.dev/packages/retrofit

Looks like they inspired from you guys.

Would be nice to have a comparison.

**Comment by techouse** [comment]
> Would be nice to have a comparison.

Not sure what the purpose of that would be 🤷, however, right off the bat you can see that the *main* difference is that https://pub.dev/packages/retrofit depends on https://pub.dev/packages/dio whereas this package depends on https://pub.dev/packages/http.

**Comment by adrianvintu** [comment]
Interesting, that is one deal breaker for us.

Would be great to know more differences, so people could choose the package they want, according to their needs.

**Comment by techouse** [comment]
We open source package maintainers should focus our limited time on developing features and fixing bugs.

With the abundance of options available on https://pub.dev people should *always* do their *own* research and decide what *they* want.

**Comment by adrianvintu** [comment]
Open source package maintainers decide  on their own where they spend their limited time.

Some do only dev, some doc, some answer questions, some provide help.

Each developer is unique.

Also, developers do not tell other people what they *should* do with their time. It's highly unpolite.
