### ISSUE TITLE
how can I send application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by humazed** [lejard-h/chopper#64]
I didn't find any example and the [test case ](https://github.com/lejard-h/chopper/blob/3fbbcc5c03e7ba83cb8c614c49a0aa3f49501dd5/chopper/test/form_test.dart) was not very helpful.

is there `@FormUrlEncoded` or any other way that I missed?

**Comment by lejard-h** [comment]
There is a `FormUrlEncodedConverter` that you can use on your chopper client which should me the default one

```dart
final chopper = ChopperClient(
    converter: FormUrlEncodedConverter(),
  );
```

You can also use a `FactoryConverter`

```dart
@FactoryConverter(request: convertRequest)
@Post()
Future<Response> postForm(@Body() Map<String, String> fields);

@FactoryConverter(request: convertRequest)
@Post()
Future<Response> postForm(@Field() String foo);

Request convertForm(Request req) =>
    applyHeader(req, contentTypeKey, formEncodedHeaders);
```

I added test case here https://github.com/lejard-h/chopper/blob/master/chopper/test/test_service.dart#L58

**Comment by humazed** [comment]
Ok, this will solve my problem, but I think this should be `@FormUrlEncoded` as a convenient annotation.
