### ISSUE TITLE
Unsuccessful API calls throw a Response

### ISSUE THREAD

**Issue by andreidiaconu** [lejard-h/chopper#68]
If an API call is unsuccessful (not in the 200-300 response code range), an exception is thrown. Upon further inspection, I see it's not actually an exception. The `send` method from the base ChopperClient throws the Response instead of returning it. I think it was meant to be returned rather than thrown. Here is the line I am talking about:
https://github.com/lejard-h/chopper/blob/dab25dee29089e92df1eeece3304bb3cd02bf650/chopper/lib/src/base.dart#L193

If this was intentional, I don't think it's a good choice. Exceptions should be thrown in _exceptional_ cases. Non-200 responses are expected results in most APIs and should be handled with business logic by users of this library, rather than catching exceptions.

**Comment by HaithamSheshtawy** [comment]
I face the same issue.

**Comment by andreidiaconu** [comment]
For now, I am catching exceptions of type `Response` and treating non-200
responses this way, as a temporary solution.

Btw, tried forking and making the change myself, but could not easily get
both the generator and the library to use git versions (I get version
resolution conflicts).

**Comment by lejard-h** [comment]
sorry for that, It should be fix on `2.5.0` :)
