### ISSUE TITLE
how to return Future<List>

### ISSUE THREAD

**Issue by minh98** [lejard-h/chopper#72]
how to return Future<List> from my object

**Comment by MahdiPishguy** [comment]
@minh98 whats your mean as return Future<List>? could you explain more?

**Comment by minh98** [comment]
@MahdiPishguy  i want to return a future of list object, future<list<object>>

**Comment by MahdiPishguy** [comment]
@minh98 this is very basic, whats your problem

**Comment by minh98** [comment]
@MahdiPishguy i mean flutter of list custom object

**Comment by lejard-h** [comment]
See documentations for `Converter`
https://hadrien-lejard.gitbook.io/chopper/converters/converters
