### ISSUE TITLE
'Response<dynamic>' is not a subtype of type 'Response<List<NetChannel>>' in type cast

### ISSUE THREAD

**Issue by HuguesBadzou** [lejard-h/chopper#74]
Hello,

I'm using Chopper with Jaguar_serializer libraries, I followed all steps but I have an exception on casting when I try to get a List of object here it is :
`[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'Response<dynamic>' is not a subtype of type 'Response<List<NetChannel>>' in type cast
`

Thanks for your help.

**Comment by HuguesBadzou** [comment]
So I can conclude that it's safer to use json_serializer instead of jaguar_serializer. I solved my issue.

**Comment by tobybonhof** [comment]
Having same issue any ideas?
