### ISSUE TITLE
http.MultipartFile not found in auto generated chopper.dart

### ISSUE THREAD

**Issue by josephchenghmlet** [lejard-h/chopper#75]
Hi, i've tried to add `MultipartFile` which is from `package:http/http.dart as http` but the auto generated chopper file return error. 

Followed #55, #65 

How do I send multiple Multipart files with same multipart key?
 
`chopper: ^3.0.0`
`chopper_generator: ^3.0.0`

```dart

// api_service.dart
...
import 'package:http/http.dart' as http;
...
@Post(path: "support/", headers: {"Authorization": ""})
  @multipart
  Future<Response> submitNewTicket({
    ...
    @PartFile('attachment') List<http.MultipartFile> attachments,
  });
...
```

```dart
// api_service.chopper.dart

Future<Response> submitNewTicket(
      {List<MultipartFile> attachments}) { // error red line at `MultipartFile`
    final $url = 'support/';
    final $headers = {'Authorization': ''};
    final $parts = <PartValue>[
      PartValueFile<List<MultipartFile>>('attachment', attachments) // error red line at `MultipartFile`
    ];
    final $request = Request('POST', $url, client.baseUrl,
        parts: $parts, multipart: true, headers: $headers);
    return client.send<dynamic, dynamic>($request);
  }
```

**Comment by MahdiPishguy** [comment]
@josephchenghmlet could you resolve your problem?

**Comment by josephchenghmlet** [comment]
Hi @MandiPishguy, I've switched to`dio` temporary for post multipartfile.

**Comment by josephchenghmlet** [comment]
Welcome back @lejard-h

**Comment by lejard-h** [comment]
aliased import seems difficult to handle with source_gen, I can't fin any resource to help me.

But you can change your import to `import 'package:http/http.dart' show MultipartFile;` or just `import 'package:http/http.dart';`

**Comment by josephchenghmlet** [comment]
Hi @lejard-h, thank you. Let me try and update you if there's outcome.

**Comment by daniel-v** [comment]
It's the exact same thing with `BuiltValue`. From some reason, code generators, in general, are having difficulty with library aliases.

**Comment by IanWorthington** [comment]
I think I'm having this same issue. If I

import 'package:chopper/chopper.dart' as ch;

then my generated code does NOT contain the import prefix.

**Comment by erlangparasu** [comment]
any update?

**Comment by erlangparasu** [comment]
@lejard-h Thanks `import 'package:http/http.dart' show MultipartFile;` works for me, because in my service class also contains Response class from chopper. `show MultipartFile` prevent conflicting imported Response class
