### ISSUE TITLE
Multiple multipartFiles with same field name

### ISSUE THREAD

**Issue by josephchenghmlet** [lejard-h/chopper#77]
Is there an alternative to pass multiple multipartFiles with same field name?
This issue was issued from [http #277](https://github.com/dart-lang/http/issues/277).

**Comment by humazed** [comment]
In chopper, you can send multiple files with the same name,
example:

```dart
  @Post(path: "store/orders")
  @multipart
  Future<Response<Order>> createTripOrder(
    @Part("trip") int trip,
    @PartFile("images[]") List<MultipartFile> images,
  );

```

**Comment by josephchenghmlet** [comment]
Hi @humazed, thanks! I'll try your answer. However, do you have suggestion for #75?

**Comment by Purvik** [comment]
@humazed  If you can answer this one I am getting trouble with single file upload
https://github.com/lejard-h/chopper/issues/129
