### ISSUE TITLE
separate request and response classes

### ISSUE THREAD

**Issue by MahdiPishguy** [lejard-h/chopper#82]
when i try to communicate with webserver i have only one `BuiltValue` class and all of request field and response fields are the same class name such as `BuiltRegisterResponse`, and that work fine,

```dart
@Post(path: '/register')
Future<Response<BuiltRegisterResponse>> registerUser(@Body() BuiltRegisterResponse body);
```

now i'm trying to separate them, this means separate request `BuiltValue` class and response `BuiltValue` class, for example:

```dart
@Post(path: '/register')
Future<Response<BuiltRegisterResponse>> registerUser(@Body() BuiltRegisterRequest body);
```
in this structure i get `NULL` and it doesn't work fine

in `BuiltRegisterRequest` class i have only `mobile_number` field` but in `BuiltRegisterResponse` i have more fields which server return that,

**Comment by lejard-h** [comment]
Hi @MahdiPishguy 
What do you mean you are getting `NULL` ? 
And what do you want chopper package to do, the issue seems to be more related to built_value package

**Comment by MahdiPishguy** [comment]
@lejard-h i think i found what was error. i'll close issue test more again
