### ISSUE TITLE
Mocking http responses

### ISSUE THREAD

**Issue by matthewfx** [lejard-h/chopper#84]
Hi,

I'm new to Flutter. I'm wondering if there is a way of mocking http responses in order to unit test i.e. if converters work as expected etc.

Cheers,

mat

**Comment by matthewfx** [comment]
Actually, I've found how to do it in one of your examples. Sorry...

**Comment by Sumit258000** [comment]
Can you please mention here example link and your experience with mockito and chopper with implementing flutter test

**Comment by techouse** [comment]
> Can you please mention here example link and your experience with mockito and chopper with implementing flutter test

Here you go https://github.com/lejard-h/chopper/issues/478#issuecomment-1676337794

**Comment by Sumit258000** [comment]
I am new to unit testing. It will be so great if you add some guide to utilise `swagger_dart_code_generator` files to mock remote repositories. @techouse

**Comment by techouse** [comment]
@Sumit258000 with all due respect that's a separate package. Please direct your request to its maintainers.
