### ISSUE TITLE
change baseUrl realtime

### ISSUE THREAD

**Issue by MahdiPishguy** [lejard-h/chopper#85]
how can i change `baseUrl` in the library like with `retrofit` real time?

**Comment by romatroskin** [comment]
yep, need this for flavouring too

**Comment by windrunner414** [comment]
+1 need it
now a workaround is extends ChopperClient and let baseUrl not final 
why not allow to set baseUrl realtime in ChopperClient?

**Comment by erlangp** [comment]
maybe you mean: change baseUrl on "runtime" :)

**Comment by JEuler** [comment]
Also, you can use the interceptor like that:
`request.copyWith(baseUrl: SharedPrefs.localStorage.getString(currentBaseUrl));`

**Comment by JEuler** [comment]
@lejard-h @stewemetal What do you think about making the baseUrl non final and setBaseUrl method? This is not very big issue in my opinion. The interceptor is okay way of doing this, btw.

**Comment by stewemetal** [comment]
**I'm actually against allowing runtime `baseUrl` changing.** Retrofit (on Android) doesn't support it for a reason. Actually, many reasons. One of them, which is relevant here, is that if you want to do this, then you have a flaw in your overall design.

For flavoring, it's not that big of a hassle to rebuild your app. I mean, if you have to rebuild with different flavors so frequently that it impacts your development time, you have bigger/different problems to attend to. :)
You can define getters in an abstract class, let's say `StringResources`, and override them in subclasses for each flavor, like `DevStringResources`, `ProdStringResources`, etc.
Then you need to implement some business logic - maybe with a facade pattern -, to decide which one is used in runtime.
(Flutter/Dart *really* needs a more sophisticated/integrated solution for flavoring - like what is available on Android, or iOS - , but... yeah, we need these kind of workarounds at the moment...)

On the other hand, how about simply creating a new `ChopperClient` instance when you need another `baseUrl`? It would clearly indicate the intent of changing the `baseUrl` in your code (actually, it will *scream* that something's happening there). If someone else gets to read your code, or may I say, run and debug it, they will more easily find *that one misbehaving piece of code* that may "accidentally" change the `baseUrl` of every network call. (This is kind of an edge case, but you get the idea.)
Also, Dart's garbage collector is actually optimized for fast-paced object creation and destruction, so it won't even have a performance impact. Not that creating a few new objects every once in a while would make a difference anyway. Flutter does it with every `Widget` rebuild pass.

From the library point of view, the less mutability we have, the less bugs we can introduce.

**Comment by erlangp** [comment]
i just want to encrypt the url, and decrypt later when needed..

**Comment by stewemetal** [comment]
What is your use-case for doing that?

**Comment by JEuler** [comment]
@stewemetal Thank you very much for this detailed point of view. I agree that this is not clean thing. Regarding flavors - I'm using the AppConfig approach for this type of things and just chaning run configurations. 

After reading your thoughts I "rethink" about the "not so big issue" and agree that this is not that should be allowed, just for simplicity for developers using this lib :)

**Comment by JEuler** [comment]
@erlangp What about using the interceptor for this task? 
`request.copyWith(baseUrl: SharedPrefs.localStorage.getString(decrypt(currentBaseUrl)));`

And when saving: encrypt?

**Comment by JEuler** [comment]
https://github.com/lejard-h/chopper/pull/135

**Comment by erlangp** [comment]
@JEuler encrypted url in NDK.. decrypt on runtime..

**Comment by JEuler** [comment]
But you can anyway save that thing on sharedprefs and interceptor will see when there are value to use, is that okay?

**Comment by JEuler** [comment]
@erlangp ?

**Comment by erlangp** [comment]
request.copyWith(baseUrl: decrypt( getStringFromNdk() ));

**Comment by JEuler** [comment]
@erlangp Yeah, something like that. So, can we close the issue? :)

**Comment by erlangp** [comment]
@MahdiPishguy @JEuler i think yes.. :) thanks

**Comment by JEuler** [comment]
@stewemetal @lejard-h We can close it for now I think, I've added note here 
https://github.com/lejard-h/chopper/pull/135
