### ISSUE TITLE
Socket exception is not handled like retrofit

### ISSUE THREAD

**Issue by Faiyyaz** [lejard-h/chopper#86]
E/flutter (12409): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed host lookup: 'jsonplaceholder.typicode.com' (OS Error: No address associated with hostname, errno = 7)
E/flutter (12409): #0      IOClient.send (package:http/src/io_client.dart:33:23)
E/flutter (12409): <asynchronous suspension>
E/flutter (12409): #1      ChopperClient.send (package:chopper/src/base.dart:171:40)
E/flutter (12409): <asynchronous suspension>
E/flutter (12409): #2      _$MyService.getPosts (package:primetime/api/my_service.chopper.dart:20:19)
E/flutter (12409): #3      _SignInScreenState.getBody.<anonymous closure> (package:primetime/ui/screens/sign_in_screen.dart:66:67)
E/flutter (12409): <asynchronous suspension>
E/flutter (12409): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (12409): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (12409): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (12409): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (12409): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (12409): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (12409): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (12409): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (12409): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (12409): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (12409): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (12409): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (12409): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (12409): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (12409): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (12409): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (12409): #20     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (12409): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (12409):

**Comment by MahdiPishguy** [comment]
@Faiyyaz you are getting `OS Error: No address associated with hostname, errno = 7` error, that means maybe you don't have internet connection or that have some other proxy which that avoid connecting to the server

**Comment by lejard-h** [comment]
It just seems to be a regular network exception like @MahdiPishguy said.
Not related to chopper.

**Comment by VadyaVL** [comment]
Hi all.
@lejard-h I've got same error while my app starting, and using FutureBuilder.
Internet connection are enabled.

Why this happen? How can I pre-load some information?
future for FutureBuilder created in initState.
