### ISSUE TITLE
Unhandled Exception on ErrorResponse

### ISSUE THREAD

**Issue by Faiyyaz** [lejard-h/chopper#88]
E/flutter (13132): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Instance of 'Response<dynamic>'
E/flutter (13132): #0      ChopperClient.send (package:chopper/src/base.dart:193:7)
E/flutter (13132): <asynchronous suspension>
E/flutter (13132): #1      _$MyService.getPosts (package:primetime/api/my_service.chopper.dart:21:19)
E/flutter (13132): #2      _SignInScreenState.getBody.<anonymous closure> (package:primetime/ui/screens/sign_in_screen.dart:68:67)
E/flutter (13132): <asynchronous suspension>
E/flutter (13132): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (13132): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (13132): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (13132): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (13132): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (13132): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (13132): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (13132): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (13132): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (13132): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (13132): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (13132): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (13132): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (13132): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (13132): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (13132): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (13132): #19     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (13132): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (13132):

**Comment by MahdiPishguy** [comment]
@Faiyyaz what's your problem. as sending error log, that couldn't help us to understand where cause of problem
