### ISSUE TITLE
chopperLogger level config

### ISSUE THREAD

**Issue by BugsBunnyBR** [lejard-h/chopper#90]
Hey, how to configure chopperLogger level?
I am trying to use `HttpLoggingInterceptor`, but chopperLogger keeps ignoring the log requests.
It would be a good idea to document it.

**Comment by marcos930807** [comment]
// Chopper already uses the Logger package. Printing the logs to the console requires
// the following setup.
void _setupLogging() {
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((rec) {
    print('${rec.level.name}: ${rec.time}: ${rec.message}');
  });
}
Execute this at startUp

**Comment by BugsBunnyBR** [comment]
@marcos930807 thanks.
There should be a sample in the README.md showing how to use it. It took me hours to figure it out.
