### ISSUE TITLE
"Avoid using braces in interpolation when not needed" warning

### ISSUE THREAD

**Issue by boylenssen** [lejard-h/chopper#96]
I would like to keep my Dart Analysis clean, but the generated files with string interpolation with using curly braces while not necessary (for paths).

Can this be fixed?

![image](https://user-images.githubusercontent.com/5054262/65685336-03ff7180-e062-11e9-9271-781ccac99947.png)

![image](https://user-images.githubusercontent.com/5054262/65685355-0feb3380-e062-11e9-892b-fd943ea4a1b1.png)

**Comment by Nathagamelle** [comment]
Still the case in Nov 2021
