### ISSUE TITLE
FormatException (FormatException: Unexpected end of input (at character 1)

### ISSUE THREAD

**Issue by sarinupreti** [lejard-h/chopper#98]
![image](https://user-images.githubusercontent.com/18618641/65982291-bb4d1b80-e49a-11e9-9766-3f2e953a1690.png)

**Comment by sarinupreti** [comment]
getting this error multiple times in chopper generated code.

**Comment by daniel-v** [comment]
I believe the error is not chopper related. You will get this kind of error when you try to json decode a response that has 0 bytes in them. There is nothing to decode. Double check that the response has content.

**Comment by lejard-h** [comment]
If you still have the error, try to restart you analyzer or clear pub cache, but I don't think this is related to chopper

**Comment by MangeshKadam** [comment]
I have similar issue. My api returns 200 in some cases and 204 in some cases. Default converted is json. It throws exception when response code is 204 as response is empty. How to handle this scenario?

**Comment by dutsky** [comment]
It seems it's not really"somewhere else" problem, but related with JsonConverter()

Some servers return 204 if they don't have any content to return: https://restfulapi.net/http-status-204-no-content/
If you have JsonConverter() enabled as converter and ChopperClient receives 204 with empty body, it pass Response to the converter and calling `_tryDecodeJson(body)` with body == "" which fails with FormatException
